"use client";

import React, { createContext, useCallback, useContext, useEffect, useMemo, useSyncExternalStore } from "react";
import { Languages } from "lucide-react";

export type AdminLanguage = "zh" | "en" | "ru";

type TranslationValues = Record<string, string | number>;

type AdminLanguageContextValue = {
  language: AdminLanguage;
  setLanguage: (language: AdminLanguage) => void;
  t: (message: string, values?: TranslationValues) => string;
};

const STORAGE_KEY = "jinyu_admin_language";
const LANGUAGE_CHANGE_EVENT = "jinyu-admin-language-change";

const zh: Record<string, string> = {
  "Language": "语言",
  "Chinese": "中文",
  "English": "英文",
  "Russian": "俄语",
  "Admin": "管理后台",
  "ADMIN": "管理后台",
  "Admin Portal": "管理门户",
  "Please sign in to access the management dashboard.": "请登录以访问管理后台。",
  "Sign In": "登录",
  "Sign Out": "退出登录",
  "Overview": "概览",
  "Analytics": "数据分析",
  "CRM": "客户关系管理",
  "Products": "产品",
  "Orders": "订单",
  "Quotes": "报价询盘",
  "Distributors": "经销商",
  "Messages": "消息",
  "Newsletter": "邮件订阅",
  "Website Content": "网站内容",
  "Settings": "设置",
  "News & Blog": "新闻与博客",
  "Admin Users": "管理员用户",
  "Documentation": "使用文档",
  "Total Revenue": "总收入",
  "Total Orders": "订单总数",
  "Total Products": "产品总数",
  "Low Stock": "库存不足",
  "New Quotes": "新报价询盘",
  "Distributor Apps": "经销商申请",
  "Unread Messages": "未读消息",
  "Subscribers": "订阅用户",
  "Recent Orders": "最近订单",
  "View All": "查看全部",
  "Customer": "客户",
  "Date": "日期",
  "Amount": "金额",
  "Status": "状态",
  "No orders yet": "暂无订单",
  "Search products...": "搜索产品……",
  "Add Product": "添加产品",
  "Product": "产品",
  "Category": "类别",
  "Stock": "库存",
  "Actions": "操作",
  "Wholesale": "批发价",
  "No products found": "未找到产品",
  "Search orders...": "搜索订单……",
  "All statuses": "所有状态",
  "ID": "编号",
  "Delete": "删除",
  "Shipping Details": "配送详情",
  "Items Ordered": "订单商品",
  "No orders found": "未找到订单",
  "Cancel": "取消",
  "Save": "保存",
  "Saving...": "正在保存……",
  "New": "新建",
  "Quoted": "已报价",
  "Closed": "已关闭",
  "Quantity": "数量",
  "Product Interest": "意向产品",
  "Message": "留言",
  "Project Type": "项目类型",
  "Phone": "电话",
  "No quote requests found": "未找到报价询盘",
  "Approved": "已批准",
  "Rejected": "已拒绝",
  "Experience": "从业经验",
  "Products Interest": "意向产品",
  "No distributor applications found": "未找到经销商申请",
  "NEW": "新消息",
  "Unread": "未读",
  "Read": "已读",
  "No messages found": "未找到消息",
  "Add Subscriber": "添加订阅用户",
  "Email": "电子邮箱",
  "Subscribed": "订阅时间",
  "Active": "有效",
  "Remove": "移除",
  "No subscribers yet": "暂无订阅用户",
  "Broadcast Email": "群发邮件",
  "Subject": "主题",
  "Message Body": "邮件正文",
  "Send Broadcast": "发送群发邮件",
  "Hero Slider": "首页轮播图",
  "Hero Headline": "主标题",
  "Sub-headline": "副标题",
  "Image URL": "图片链接",
  "Stats Bar": "数据栏",
  "Value": "数值",
  "Label": "标签",
  "Manufacturing Section": "制造实力板块",
  "Headline": "标题",
  "Body": "正文",
  "Image": "图片",
  "Upload": "上传",
  "Preview": "预览",
  "Featured Product Lines": "精选产品系列",
  "Title": "标题",
  "Description": "描述",
  "Store Settings": "商店设置",
  "Branding": "品牌设置",
  "Store Name": "商店名称",
  "Store Logo": "商店标志",
  "Contact Information": "联系信息",
  "Support Email": "客服邮箱",
  "Support Phone": "客服电话",
  "Office Address": "办公地址",
  "Social Media Links": "社交媒体链接",
  "Currency & Pricing": "货币与定价",
  "Exchange Rates": "汇率",
  "Minimum Order Quantity": "最小起订量",
  "Create Blog Post": "创建博客文章",
  "Edit Blog Post": "编辑博客文章",
  "Compose and publish updates for the website.": "撰写并发布网站动态。",
  "Slug": "网址别名",
  "Excerpt": "摘要",
  "Featured Image": "特色图片",
  "Content (Markdown)": "正文（Markdown）",
  "Publish": "发布",
  "Update": "更新",
  "Search articles...": "搜索文章……",
  "New Post": "新建文章",
  "Article": "文章",
  "Published": "发布时间",
  "Edit": "编辑",
  "No blog posts found": "未找到博客文章",
  "Add an administrator": "添加管理员",
  "Create a secure account for a new dashboard administrator.": "为新的后台管理员创建安全账户。",
  "Name": "姓名",
  "Temporary password": "临时密码",
  "Confirm password": "确认密码",
  "Create administrator": "创建管理员",
  "Add New Product": "添加新产品",
  "Edit Product Listing": "编辑产品信息",
  "Discard": "放弃更改",
  "Save Product": "保存产品",
  "Update Product": "更新产品",
  "Product Details": "产品详情",
  "Product Name *": "产品名称 *",
  "Category *": "类别 *",
  "Initial Stock *": "初始库存 *",
  "Current Stock *": "当前库存 *",
  "External Image URL (Optional)": "外部图片链接（可选）",
  "Media Management": "媒体管理",
  "Main Image": "主图",
  "Main Preview": "主图预览",
  "Click or drag to upload primary image": "点击或拖拽上传主图",
  "Gallery Images": "图库图片",
  "Loading product details...": "正在加载产品详情……",
  "Street Lamps": "路灯",
  "Landscape Lamps": "景观灯",
  "Ceiling Lights": "吸顶灯",
  "Wall Sconces": "壁灯",
  "Pendant Lamps": "吊灯",
  "Industrial Lighting": "工业照明",
  "e.g. Skyline Boulevard Street Lamp": "例如：天际大道路灯",
  "Detailed product specifications and features...": "填写详细的产品规格与特点……",
  "Please enter a valid stock level.": "请输入有效的库存数量。",
  "Product created successfully!": "产品创建成功！",
  "Failed to create product.": "产品创建失败。",
  "Product updated successfully!": "产品更新成功！",
  "Failed to update product details.": "产品详情更新失败。",
  "Product details could not be found.": "未找到产品详情。",
  "Failed to load product details.": "产品详情加载失败。",
  "Admin User Guide": "管理后台使用指南",
  "Save as PDF": "另存为 PDF",
  "Step-by-step guidance for managing the website. This guide is publicly available and does not require an administrator login.": "网站管理分步指南。本指南可公开访问，无需管理员登录。",
  "Getting Started": "快速入门",
  "Navigation Guide": "导航指南",
  "Product Management": "产品管理",
  "Add a Product": "添加产品",
  "Update Stock": "更新库存",
  "Upload Product Images": "上传产品图片",
  "Order Management": "订单管理",
  "View Order Details": "查看订单详情",
  "Update Order Status": "更新订单状态",
  "Customer Relationship Management": "客户关系管理",
  "CRM Dashboard": "CRM 仪表盘",
  "Contacts and Companies": "联系人与公司",
  "Sales Pipeline": "销售管道",
  "Tasks and Activity History": "任务与活动记录",
  "Customize the Homepage": "自定义首页",
  "Manage the Hero Slider": "管理首页轮播图",
  "Upload Homepage Images": "上传首页图片",
  "Configure Store Settings": "配置商店设置",
  "Customer Engagement": "客户互动",
  "Quote Requests": "报价询盘",
  "Distributor Applications": "经销商申请",
  "Contact Messages": "联系消息",
  "Newsletter Subscribers": "邮件订阅用户",
  "Account Management": "账户管理",
  "Review revenue, orders, products, low-stock alerts, and recent activity from the Overview tab.": "在“概览”标签页查看收入、订单、产品、库存不足提醒和最近活动。",
  "Use the sidebar to move between store management areas. On smaller screens, use the menu button to open it.": "使用侧边栏切换各管理区域。在小屏幕设备上，请使用菜单按钮打开侧边栏。",
  "Open Products, select Add Product, complete the product details, upload images, then save it to the catalogue.": "打开“产品”，选择“添加产品”，填写产品详情并上传图片，然后保存到产品目录。",
  "Find the product in Products, edit its stock quantity, and confirm the change. Low-stock alerts update automatically.": "在“产品”中找到相应商品，修改库存数量并确认。库存不足提醒将自动更新。",
  "When adding or editing a product, upload JPG, PNG, or WebP files. The first image becomes the main product image.": "添加或编辑产品时，可上传 JPG、PNG 或 WebP 文件。第一张图片将作为产品主图。",
  "Open Orders and select an order to see customer details, shipping information, items, and status.": "打开“订单”并选择一笔订单，即可查看客户详情、配送信息、商品和状态。",
  "Expand an order and choose Pending, Processing, Shipped, Delivered, or Cancelled. The change saves automatically.": "展开订单并选择待处理、处理中、已发货、已送达或已取消，系统会自动保存更改。",
  "Open CRM from the left menu to review pipeline value, weighted forecast, won revenue, win rate, upcoming work, and recent customer activity.": "从左侧菜单打开 CRM，查看管道金额、加权预测、成交收入、成交率、待办工作和近期客户活动。",
  "Create complete contact and company profiles, assign lifecycle and lead statuses, score prospects, add tags, schedule follow-ups, and export filtered contacts to CSV.": "创建完整的联系人和公司档案，设置生命周期与线索状态、潜客评分和标签，安排跟进，并将筛选后的联系人导出为 CSV。",
  "Create revenue opportunities in Pipeline, assign contacts and companies, set value and closing dates, then move each deal through Lead, Qualified, Proposal, Negotiation, Won, or Lost.": "在销售管道中创建商机，关联联系人和公司，设置金额与预计成交日期，并推动商机依次进入线索、已确认、方案、谈判、赢单或输单阶段。",
  "Record notes, calls, emails, meetings, and tasks. Mark work complete and use the Overdue view to keep follow-ups from being missed.": "记录备注、电话、邮件、会议和任务。完成后进行标记，并使用“逾期”视图避免遗漏跟进。",
  "Use Website Content to update the hero, statistics, manufacturing section, and featured products, then save your changes.": "在“网站内容”中更新首页主视觉、数据、制造实力和精选产品，然后保存更改。",
  "Use Website Content to add, remove, reorder, upload, or paste URLs for hero background slides. The homepage rotates them automatically and provides visitor controls.": "在“网站内容”中添加、移除、排序或上传轮播背景图，也可粘贴图片链接。首页会自动轮播并提供访客控制。",
  "Upload hero slider or manufacturing images, or enter direct image URLs. Check each preview before saving.": "上传首页轮播图或制造实力图片，也可直接输入图片链接。保存前请检查预览。",
  "Use Settings to maintain store contact details, branding, social links, exchange rates, and wholesale minimum order quantity.": "在“设置”中维护商店联系方式、品牌、社交媒体链接、汇率和批发最小起订量。",
  "Review requests in Quotes, open one for details, and update its status as the opportunity progresses.": "在“报价询盘”中查看请求，打开详情，并根据商机进展更新状态。",
  "Review applicants in Distributors, check their business details, then mark each application as approved, rejected, or under review.": "在“经销商”中查看申请人及其业务详情，然后将申请标记为已批准、已拒绝或审核中。",
  "Open Contacts to read customer messages and mark them as read after review.": "打开“联系消息”阅读客户留言，查看后将其标记为已读。",
  "Manage active subscribers in Newsletter, add subscribers manually, and deactivate addresses when required.": "在“邮件订阅”中管理有效订阅用户、手动添加订阅者，并在需要时停用邮箱地址。",
  "Go to /login, enter an administrator email and password, then select Sign In.": "前往 /login，输入管理员邮箱和密码，然后选择“登录”。",
  "Use the account area at the bottom of the admin sidebar and select Sign Out to end the session.": "使用管理后台侧边栏底部的账户区域，选择“退出登录”结束会话。",
  "Need additional help?": "还需要帮助？",
  "Contact your site support team for help with anything not covered in this guide.": "如需解决本指南未涵盖的问题，请联系网站支持团队。",
  "Back to Dashboard": "返回管理后台",
  "Administration Manual": "后台管理手册",
  "Last updated": "最后更新",
  "Table of Contents": "目录",
  "Dashboard Overview": "后台概览",
  "Need Help?": "需要帮助？",
  "Contact the website development team if you encounter an issue that is not covered in this guide.": "如果遇到本指南未涵盖的问题，请联系网站开发团队。",
  "Print / Save as PDF": "打印 / 另存为 PDF",
  "Customer 360": "客户 360° 视图",
  "Customer relationships, sales follow-up, and forecasting in one workspace.": "在一个工作区中管理客户关系、销售跟进与业绩预测。",
  "Dashboard": "仪表盘",
  "Contacts": "联系人",
  "Companies": "公司",
  "Pipeline": "销售管道",
  "Activities": "跟进活动",
  "Open pipeline": "进行中的销售管道",
  "Weighted forecast": "加权预测",
  "Average conversion": "平均转化率",
  "Settled revenue": "已结清收入",
  "Settlement rate": "结清率",
  "Pipeline health": "销售管道健康度",
  "Next actions": "下一步行动",
  "Add contact": "添加联系人",
  "Add activity": "添加活动",
  "Add deal": "添加商机",
  "Search contacts...": "搜索联系人……",
  "All owners": "所有负责人",
  "All stages": "所有阶段",
  "Company": "公司",
  "Owner": "负责人",
  "Next follow-up": "下次跟进",
  "Conversion": "转化概率",
  "No contacts found": "未找到联系人",
  "New inquiry": "新询盘",
  "New inquiries": "新询盘",
  "Quoted Price": "已报价",
  "Negotiating price": "价格协商中",
  "PI pending confirmation": "形式发票待确认",
  "Deposit Received": "已收到定金",
  "Customs clearance and shipment": "清关与发货",
  "Full payment settled": "全款已结清",
  "Contact details": "联系人详情",
  "Contact name": "联系人姓名",
  "Source": "来源",
  "Notes": "备注",
  "Deal value": "商机金额",
  "Probability": "成交概率",
  "Expected value": "预计金额",
  "Activity type": "活动类型",
  "Due date": "截止日期",
  "Completed": "已完成",
  "Pending": "待处理",
  "Call": "电话",
  "Meeting": "会议",
  "Email follow-up": "邮件跟进",
  "Task": "任务",
  "Analytics Overview": "数据分析概览",
  "Track website performance and visitor behavior.": "跟踪网站表现与访客行为。",
  "7 Days": "7 天",
  "30 Days": "30 天",
  "90 Days": "90 天",
  "Year to Date": "今年至今",
  "All Time": "全部时间",
  "Visitors": "访客数",
  "Page Views": "页面浏览量",
  "Sessions": "访问次数",
  "Bounce Rate": "跳出率",
  "Avg. Session": "平均访问时长",
  "Traffic Overview": "流量概览",
  "Top Pages": "热门页面",
  "Traffic Sources": "流量来源",
  "Devices": "设备",
  "Browsers": "浏览器",
  "Countries": "国家/地区",
  "Direct Navigation": "直接访问",
  "Google Search": "Google 搜索",
  "Search Engines": "搜索引擎",
  "Social Networks": "社交网络",
  "Desktop": "桌面设备",
  "Mobile": "移动设备",
  "Tablet": "平板设备",
  "Other": "其他",
  "No analytics data available for this period.": "此时间段暂无分析数据。",
  "Refresh": "刷新",
  "View Site": "查看网站",
  "Loading data...": "正在加载数据……",
  "Saved!": "已保存！",
  "from {count} orders": "来自 {count} 笔订单",
  "{count} pending": "{count} 笔待处理",
  "{count} in stock": "{count} 件有库存",
  "items below 5 units": "库存低于 5 件的产品",
  "All": "全部",
  "Processing": "处理中",
  "Shipped": "已发货",
  "Delivered": "已送达",
  "Cancelled": "已取消",
  "Inactive": "已停用",
  "Unknown": "未知",
  "N/A": "暂无",
  "No quote requests yet": "暂无报价询盘",
  "No distributor applications yet": "暂无经销商申请",
  "No messages yet": "暂无消息",
  "{count} active": "{count} 个有效订阅",
  "Export CSV": "导出 CSV",
  "Add subscriber email...": "添加订阅邮箱……",
  "Newsletter Subject": "邮件主题",
  "Email body content...": "输入邮件正文……",
  "Send via Email Client": "通过邮件客户端发送",
  "Opens your default email client with BCC to all active subscribers.": "打开默认邮件客户端，并将所有有效订阅用户添加到密送名单。",
  "Analytics & Reports": "数据分析与报告",
  "Stock update failed: {message}": "库存更新失败：{message}",
  "Update failed: {message}": "更新失败：{message}",
  "Delete failed: {message}": "删除失败：{message}",
  "Failed: {message}": "操作失败：{message}",
  "Delete this product?": "确定要删除此产品吗？",
  "Delete this order?": "确定要删除此订单吗？",
  "Delete quote?": "确定要删除此报价询盘吗？",
  "Delete distributor application?": "确定要删除此经销商申请吗？",
  "Delete message?": "确定要删除此消息吗？",
  "Enter a valid email.": "请输入有效的电子邮箱。",
  "Failed.": "操作失败。",
  "Steps:": "步骤：",
  "Need Additional Help?": "还需要帮助？",
  "Contact Support": "联系支持团队",
  "Step-by-step instructions for managing your Jinyu Capital website through the admin panel.": "通过管理后台维护 Jinyu Capital 网站的分步说明。",
  "Failed to load dashboard data.": "管理后台数据加载失败。",
  "Passwords do not match.": "两次输入的密码不一致。",
  "Please fill in all required fields.": "请填写所有必填字段。",
  "Blog post updated successfully!": "博客文章更新成功！",
  "Blog post created successfully!": "博客文章创建成功！",
  "Failed to save blog post.": "博客文章保存失败。",
  "Are you sure you want to delete this blog post?": "确定要删除这篇博客文章吗？",
  "Edit what visitors see on the homepage.": "编辑访客在首页看到的内容。",
  "Save All Changes": "保存全部更改",
  "Slides rotate automatically every six seconds. Visitors can pause or navigate manually.": "轮播图每六秒自动切换，访客也可暂停或手动切换。",
  "Add slide": "添加轮播图",
  "Hero Sub-headline": "首页副标题",
  "Hero slide {count} preview": "首页轮播图 {count} 预览",
  "Slide {count}": "第 {count} 张",
  "Move slide {count} left": "将第 {count} 张向左移动",
  "Move slide {count} right": "将第 {count} 张向右移动",
  "Remove slide {count}": "移除第 {count} 张",
  "Upload replacement image": "上传替换图片",
  "Section Headline": "板块标题",
  "Section Body Text": "板块正文",
  "Manufacturing Image URL": "制造实力图片链接",
  "Or Upload Manufacturing Image": "或上传制造实力图片",
  "Click to upload image...": "点击上传图片……",
  "Manufacturing preview": "制造实力图片预览",
  "Product {count}": "产品 {count}",
  "Or Upload New Image": "或上传新图片",
  "Save Website Content": "保存网站内容",
  "Manage contact info, branding, and integrations.": "管理联系信息、品牌和集成设置。",
  "Save Settings": "保存设置",
  "Upload your company logo. Recommended: PNG with transparent background, min 200×200px.": "上传公司标志。建议使用透明背景的 PNG 图片，最小尺寸为 200×200 像素。",
  "Full mailing address...": "完整邮寄地址……",
  "Facebook URL": "Facebook 链接",
  "Instagram URL": "Instagram 链接",
  "TikTok URL": "TikTok 链接",
  "AUD Exchange Rate (1 USD =)": "澳元汇率（1 美元 =）",
  "NGN Exchange Rate (1 USD =)": "奈拉汇率（1 美元 =）",
  "Global Wholesale MOQ": "全球批发最小起订量",
  "Compose and publish articles to your website.": "撰写文章并发布到网站。",
  "Title *": "标题 *",
  "Enter article title": "输入文章标题",
  "Slug (URL) *": "网址别名（URL）*",
  "Excerpt *": "摘要 *",
  "Brief summary of the article for listings (1-2 sentences)": "用于文章列表的简短摘要（1–2 句话）",
  "Upload a PNG, JPG, or WEBP image. Will be uploaded to Supabase Storage.": "上传 PNG、JPG 或 WEBP 图片，文件将保存到 Supabase Storage。",
  "Content (Supports Markdown) *": "正文（支持 Markdown）*",
  "Write your article content here...": "在此撰写文章正文……",
  "Update Post": "更新文章",
  "Publish Post": "发布文章",
  "Explosion-Proof Lighting": "防爆照明",
  "Industrial Equipment": "工业设备",
  "Industry News & Insights": "行业新闻与洞察",
  "OEM/ODM Solutions": "OEM/ODM 解决方案",
  "Product Updates": "产品动态",
  "No articles found. Click \"New Post\" to create your first article!": "未找到文章。点击“新建文章”创建第一篇文章！",
  "New administrators can sign in and manage the website immediately.": "新管理员创建后即可登录并管理网站。",
  "Administrator name": "管理员姓名",
  "Email address": "电子邮箱",
  "Use at least 12 characters. Share the temporary password securely.": "请使用至少 12 个字符，并通过安全方式分享临时密码。",
  "Real-Time Traffic & User Analytics": "实时流量与用户分析",
  "Active website visitors, referring traffic links, country locales, device types, and sales revenue.": "查看在线访客、流量来源、国家/地区、设备类型和销售收入。",
  "YTD": "今年至今",
  "Export Report": "导出报告",
  "Active Users Now": "当前在线用户",
  "Live visitors active in last 5 minutes": "过去 5 分钟内的在线访客",
  "15-Min Active Visitors": "15 分钟活跃访客",
  "Unique session visitors in last 15 mins": "过去 15 分钟内的独立会话访客",
  "24-Hour Active Users": "24 小时活跃用户",
  "Unique user sessions recorded today": "今天记录的独立用户会话",
  "Traffic Sources & Referring Links": "流量来源与引荐链接",
  "Origins and acquisition links of website traffic": "网站流量的来源与获客链接",
  "{count} Pageviews": "{count} 次浏览",
  "No referral traffic recorded in this timeframe yet.": "此时间段内尚无引荐流量记录。",
  "{count} views ({percent}%)": "{count} 次浏览（{percent}%）",
  "Geographical Country Traffic": "国家/地区流量",
  "Global visitor locations & B2B distributor regions": "全球访客位置与 B2B 经销商区域",
  "No location traffic data recorded in this timeframe yet.": "此时间段内尚无地区流量数据。",
  "{count} interactions": "{count} 次互动",
  "Device Types & Browsers": "设备类型与浏览器",
  "Desktop vs Mobile vs Tablet ratio": "桌面、移动和平板设备占比",
  "No device data": "暂无设备数据",
  "Top Visited Pages & Content Traffic": "热门页面与内容流量",
  "Page URL paths with highest visitor traffic": "访客流量最高的页面路径",
  "Page URL Path": "页面路径",
  "No page views recorded in this timeframe yet.": "此时间段内尚无页面浏览记录。",
  "{count} views": "{count} 次浏览",
  "Total Sales Revenue": "销售总收入",
  "Based on {count} paid orders": "基于 {count} 笔已付款订单",
  "Average Order Value": "平均订单金额",
  "Per transaction average": "每笔交易平均值",
  "Quote & Partner Leads": "报价与合作线索",
  "{count} Inquiries": "{count} 条询盘",
  "{quotes} Quotes & {distributors} Distributor Apps": "{quotes} 条报价询盘与 {distributors} 条经销商申请",
  "Catalog Products": "目录产品",
  "{count} Items": "{count} 项产品",
  "Catalog Value: {value}": "目录价值：{value}",
  "Product Inventory & Stock Status": "产品库存与库存状态",
  "Real-time inventory levels from the products database table": "来自产品数据库的实时库存水平",
  "Category:": "类别：",
  "Product Name": "产品名称",
  "Unit Price": "单价",
  "Stock Quantity": "库存数量",
  "Catalog Valuation": "目录估值",
  "No products found in database for the selected category.": "数据库中未找到所选类别的产品。",
  "In Stock": "有库存",
  "Out of Stock": "无库存",
  "Low Stock ({count})": "库存不足（{count}）",
  "General": "其他",
  "{count} units": "{count} 件",
  "Showing top 10 of {count} products. Filter by category to view others.": "当前显示 {count} 个产品中的前 10 个，可按类别筛选查看其他产品。",
  "Direct / None": "直接访问 / 无来源",
  "Direct Locale": "本地直接访问",
  "Metric": "指标",
  "Timeframe": "时间范围",
  "Active Users (5 min)": "活跃用户（5 分钟）",
  "Active Users (15 min)": "活跃用户（15 分钟）",
  "Active Users (24 hours)": "活跃用户（24 小时）",
  "Total Page Views": "页面浏览总量",
  "Valid/Paid Orders": "有效/已付款订单",
  "Low Stock Alert Count": "库存不足提醒数量",
  "Out of Stock Count": "缺货数量",
  "Close": "关闭",
  "Close dialog": "关闭对话框",
  "Close contact details": "关闭联系人详情",
  "Unassigned": "未分配",
  "Not set": "未设置",
  "The CRM database migration has not been applied yet.": "尚未应用 CRM 数据库迁移。",
  "First name is required.": "名字为必填项。",
  "Enter a valid email address.": "请输入有效的电子邮箱。",
  "Contact updated.": "联系人已更新。",
  "Contact added.": "联系人已添加。",
  "Company name is required.": "公司名称为必填项。",
  "Company updated.": "公司已更新。",
  "Company added.": "公司已添加。",
  "Deal title is required.": "商机标题为必填项。",
  "Deal updated.": "商机已更新。",
  "Deal added to the pipeline.": "商机已添加到销售管道。",
  "Subject is required.": "主题为必填项。",
  "Activity updated.": "活动已更新。",
  "Activity recorded.": "活动已记录。",
  "Moved to {stage}.": "已移至“{stage}”。",
  "Delete this {label}? This action cannot be undone.": "确定要删除此{label}吗？此操作无法撤销。",
  "{label} deleted.": "{label}已删除。",
  "contact": "联系人",
  "company": "公司",
  "deal": "商机",
  "activity": "活动",
  "Loading your customer workspace...": "正在加载客户工作区……",
  "CRM is ready to be activated": "CRM 已可启用",
  "Apply the included CRM database migration, then refresh this page. Existing orders, quotes, distributor applications, and messages will be organized automatically.": "应用随附的 CRM 数据库迁移后刷新此页面。现有订单、报价询盘、经销商申请和消息将自动整理。",
  "Check again": "再次检查",
  "CRM data could not be loaded": "CRM 数据加载失败",
  "Try again": "重试",
  "Customer relationships": "客户关系",
  "One workspace for every relationship, deal, and follow-up.": "在一个工作区中管理所有客户关系、商机和跟进。",
  "New deal": "新建商机",
  "New contact": "新建联系人",
  "Refresh CRM": "刷新 CRM",
  "{count} overdue": "{count} 项逾期",
  "{count} active deals": "{count} 个进行中商机",
  "Probability adjusted": "已按概率加权",
  "{count} customer records": "{count} 条客户记录",
  "{count} fully settled deals": "{count} 个全款结清商机",
  "{count} closed deals": "{count} 个已关闭商机",
  "Value, volume, and probability by conversion stage": "按转化阶段查看金额、数量和成交概率",
  "View pipeline": "查看销售管道",
  "{count} deals": "{count} 个商机",
  "Add a deal to start forecasting your pipeline.": "添加商机以开始销售管道预测。",
  "Tasks and meetings that need attention": "需要关注的任务和会议",
  "Complete {subject}": "完成“{subject}”",
  "No due date": "无截止日期",
  "You are all caught up.": "所有事项均已处理。",
  "Recent relationship activity": "近期客户活动",
  "Latest notes, calls, emails, meetings, and tasks": "最新备注、电话、邮件、会议和任务",
  "View all": "查看全部",
  "No additional details": "无更多详情",
  "No activity has been recorded yet.": "尚未记录活动。",
  "Search name, email, company, phone, or tag...": "搜索姓名、邮箱、公司、电话或标签……",
  "Filter by lifecycle stage": "按生命周期阶段筛选",
  "All lifecycle stages": "所有生命周期阶段",
  "Filter by conversion stage": "按转化阶段筛选",
  "All conversion stages": "所有转化阶段",
  "Export filtered contacts": "导出筛选后的联系人",
  "Contact": "联系人",
  "Lifecycle": "生命周期",
  "Lead status": "线索状态",
  "No contact details": "无联系方式",
  "No title": "未设置职位",
  "No contacts match your filters": "没有联系人符合筛选条件",
  "Build your customer database": "建立客户数据库",
  "Try a different search term, lifecycle stage, or conversion stage.": "请尝试其他搜索词、生命周期阶段或转化阶段。",
  "Add the people your team sells to, supports, and partners with.": "添加销售、服务和合作所涉及的联系人。",
  "Add first contact": "添加第一个联系人",
  "Search companies, industries, or locations...": "搜索公司、行业或地区……",
  "Add company": "添加公司",
  "Industry not set": "未设置行业",
  "Website": "网站",
  "No companies match your search": "没有公司符合搜索条件",
  "Organize contacts by company": "按公司整理联系人",
  "Try a broader company, industry, or location search.": "请尝试更宽泛的公司、行业或地区搜索。",
  "Track accounts, partners, and prospects with their related contacts and opportunities.": "跟踪客户、合作伙伴和潜在客户，以及相关联系人和商机。",
  "Add first company": "添加第一家公司",
  "Sales pipeline": "销售管道",
  "{open} open · {weighted} weighted forecast": "进行中 {open} · 加权预测 {weighted}",
  "{probability}% probability · {value}": "{probability}% 概率 · {value}",
  "High priority": "高优先级",
  "{probability}% · {value} weighted": "{probability}% · 加权金额 {value}",
  "Move {title} to another stage": "将“{title}”移至其他阶段",
  "No deals": "暂无商机",
  "Open": "待处理",
  "Overdue": "已逾期",
  "All activity": "全部活动",
  "Reopen activity": "重新打开活动",
  "Complete activity": "完成活动",
  "General CRM activity": "常规 CRM 活动",
  "Outcome:": "结果：",
  "Nothing in this activity view": "此活动视图暂无内容",
  "Record a note, call, email, meeting, or task to keep the relationship history complete.": "记录备注、电话、邮件、会议或任务，以保持完整的客户关系历史。",
  "Edit contact": "编辑联系人",
  "Maintain a complete customer profile for sales and service.": "维护完整的客户资料，为销售和服务提供支持。",
  "First name *": "名字 *",
  "Last name": "姓氏",
  "Job title": "职位",
  "No company": "无关联公司",
  "Lifecycle stage": "生命周期阶段",
  "Conversion stage": "转化阶段",
  "New inquiry (10%)": "新询盘（10%）",
  "Applied automatically when the contact is created.": "创建联系人时自动应用。",
  "Lead score / quality (0–100)": "线索评分 / 质量（0–100）",
  "Tags (comma separated)": "标签（以逗号分隔）",
  "Internal notes": "内部备注",
  "Contact has opted in to marketing communications": "联系人已同意接收营销信息",
  "Save changes": "保存更改",
  "Edit company": "编辑公司",
  "Track an account, partner, or prospect organization.": "跟踪客户、合作伙伴或潜在客户组织。",
  "Company name *": "公司名称 *",
  "Industry": "行业",
  "Company size": "公司规模",
  "Not specified": "未指定",
  "Relationship": "关系类型",
  "City": "城市",
  "Address": "地址",
  "Edit deal": "编辑商机",
  "Create and forecast a revenue opportunity.": "创建收入商机并进行预测。",
  "Deal title *": "商机标题 *",
  "No contact": "无关联联系人",
  "Expected close": "预计成交日期",
  "Currency": "货币",
  "Used to weight this deal in the sales forecast.": "用于在销售预测中计算此商机的加权金额。",
  "Priority": "优先级",
  "Loss reason": "输单原因",
  "Deal notes": "商机备注",
  "Edit activity": "编辑活动",
  "Keep the relationship timeline complete and actionable.": "保持客户关系时间线完整且可执行。",
  "Subject *": "主题 *",
  "Related deal": "关联商机",
  "No deal": "无关联商机",
  "Details": "详情",
  "Discussion notes, agenda, or task instructions...": "讨论记录、议程或任务说明……",
  "Outcome": "结果",
  "Optional result or next step": "可选：填写结果或下一步",
  "Record activity": "记录活动",
  "Quoted price": "已报价",
  "Deposit received": "已收到定金",
  "Lost / closed": "输单 / 已关闭",
  "Website enquiry received or contact added manually": "收到网站询盘或由管理员手动添加联系人",
  "Quotation sent to the customer": "已向客户发送报价",
  "Price and 40% deposit terms under negotiation": "正在协商价格及 40% 定金条款",
  "Proforma invoice awaiting customer confirmation": "形式发票等待客户确认",
  "Customer's 40% order deposit received": "已收到客户 40% 的订单定金",
  "Order in customs clearance or shipment": "订单正在清关或发货",
  "Full order payment received and settled": "订单全款已收并结清",
  "Opportunity closed without conversion": "商机未成交并已关闭",
  "Lead": "线索",
  "Prospect": "潜在客户",
  "Opportunity": "商机",
  "Partner": "合作伙伴",
  "Attempted": "已尝试联系",
  "Contacted": "已联系",
  "Qualified": "已确认",
  "Nurturing": "培育中",
  "Unqualified": "不合格",
  "Manual": "手动添加",
  "Quote": "报价询盘",
  "Order": "订单",
  "Distributor": "经销商",
  "Import": "导入",
  "Referral": "转介绍",
  "Low": "低",
  "Normal": "普通",
  "High": "高",
  "Solo": "个人",
  "Small": "小型",
  "Medium": "中型",
  "Large": "大型",
  "Enterprise": "企业级",
  "Note": "备注",
  "Status Change": "状态变更",
  "Profile": "资料",
  "Not assigned": "未分配",
  "Lead score": "线索评分",
  "Tags": "标签",
  "No tags": "无标签",
  "Deals": "商机",
  "{count} opportunities": "{count} 个商机",
  "Add": "添加",
  "weighted": "加权",
  "No deals linked to this contact.": "此联系人尚未关联商机。",
  "Activity timeline": "活动时间线",
  "{count} recorded touchpoints": "已记录 {count} 次互动",
  "No activity recorded for this contact yet.": "此联系人尚无活动记录。",
};

const ru: Record<string, string> = {
  "Language": "Язык",
  "Chinese": "Китайский",
  "English": "Английский",
  "Russian": "Русский",
  "Admin": "Админ-панель",
  "ADMIN": "АДМИН",
  "Admin Portal": "Панель управления",
  "Please sign in to access the management dashboard.": "Пожалуйста, войдите для доступа к панели управления.",
  "Sign In": "Войти",
  "Sign Out": "Выйти",
  "Overview": "Обзор",
  "Analytics": "Аналитика",
  "CRM": "CRM",
  "Products": "Товары",
  "Orders": "Заказы",
  "Quotes": "Запросы цен",
  "Distributors": "Дистрибьюторы",
  "Messages": "Сообщения",
  "Newsletter": "Рассылка",
  "Website Content": "Контент сайта",
  "Settings": "Настройки",
  "News & Blog": "Новости и блог",
  "Admin Users": "Администраторы",
  "Documentation": "Документация",
  "Total Revenue": "Общая выручка",
  "Total Orders": "Всего заказов",
  "Total Products": "Всего товаров",
  "Low Stock": "Мало на складе",
  "New Quotes": "Новые запросы цен",
  "Distributor Apps": "Заявки дистрибьюторов",
  "Unread Messages": "Непрочитанные сообщения",
  "Subscribers": "Подписчики",
  "Recent Orders": "Последние заказы",
  "View All": "Смотреть все",
  "Customer": "Клиент",
  "Date": "Дата",
  "Amount": "Сумма",
  "Status": "Статус",
  "No orders yet": "Заказов пока нет",
  "Search products...": "Поиск товаров...",
  "Add Product": "Добавить товар",
  "Product": "Товар",
  "Category": "Категория",
  "Stock": "Остаток",
  "Actions": "Действия",
  "Wholesale": "Оптовая цена",
  "No products found": "Товары не найдены",
  "Search orders...": "Поиск заказов...",
  "All statuses": "Все статусы",
  "ID": "ID",
  "Delete": "Удалить",
  "Shipping Details": "Детали доставки",
  "Items Ordered": "Заказанные товары",
  "No orders found": "Заказы не найдены",
  "Cancel": "Отмена",
  "Save": "Сохранить",
  "Saving...": "Сохранение...",
  "New": "Новый",
  "Quoted": "Выставлен КП",
  "Closed": "Закрыт",
  "Quantity": "Количество",
  "Product Interest": "Интересующий товар",
  "Message": "Сообщение",
  "Project Type": "Тип проекта",
  "Phone": "Телефон",
  "No quote requests found": "Запросы цен не найдены",
  "Approved": "Одобрено",
  "Rejected": "Отклонено",
  "Experience": "Опыт работы",
  "Products Interest": "Интересующие товары",
  "No distributor applications found": "Заявки дистрибьюторов не найдены",
  "NEW": "НОВОЕ",
  "Unread": "Непрочитано",
  "Read": "Прочитано",
  "No messages found": "Сообщения не найдены",
  "Add Subscriber": "Добавить подписчика",
  "Email": "Эл. почта",
  "Subscribed": "Дата подписки",
  "Active": "Активен",
  "Remove": "Удалить",
  "No subscribers yet": "Подписчиков пока нет",
  "Broadcast Email": "Массовая рассылка",
  "Subject": "Тема",
  "Message Body": "Текст сообщения",
  "Send Broadcast": "Отправить рассылку",
  "Hero Slider": "Слайдер на главной",
  "Hero Headline": "Главный заголовок",
  "Sub-headline": "Подзаголовок",
  "Image URL": "URL изображения",
  "Stats Bar": "Панель статистики",
  "Value": "Значение",
  "Label": "Метка",
  "Manufacturing Section": "Раздел производства",
  "Headline": "Заголовок",
  "Body": "Основной текст",
  "Image": "Изображение",
  "Upload": "Загрузить",
  "Preview": "Предпросмотр",
  "Featured Product Lines": "Популярные линейки товаров",
  "Title": "Заголовок",
  "Description": "Описание",
  "Store Settings": "Настройки магазина",
  "Branding": "Брендинг",
  "Store Name": "Название магазина",
  "Store Logo": "Логотип магазина",
  "Contact Information": "Контактная информация",
  "Support Email": "Email поддержки",
  "Support Phone": "Телефон поддержки",
  "Office Address": "Адрес офиса",
  "Social Media Links": "Социальные сети",
  "Currency & Pricing": "Валюта и цены",
  "Exchange Rates": "Курсы валют",
  "Minimum Order Quantity": "Минимальный заказ (MOQ)",
  "Create Blog Post": "Создать запись в блоге",
  "Edit Blog Post": "Редактировать запись в блоге",
  "Compose and publish updates for the website.": "Создание и публикация материалов для сайта.",
  "Slug": "ЧПУ (Slug)",
  "Excerpt": "Анонс",
  "Featured Image": "Главное изображение",
  "Content (Markdown)": "Содержимое (Markdown)",
  "Publish": "Опубликовать",
  "Update": "Обновить",
  "Search articles...": "Поиск статей...",
  "New Post": "Новая статья",
  "Article": "Статья",
  "Published": "Опубликовано",
  "Edit": "Редактировать",
  "No blog posts found": "Статьи не найдены",
  "Add an administrator": "Добавить администратора",
  "Create a secure account for a new dashboard administrator.": "Создание защищенной учетной записи для нового администратора.",
  "Name": "Имя",
  "Temporary password": "Временный пароль",
  "Confirm password": "Подтвердите пароль",
  "Create administrator": "Создать администратора",
  "Add New Product": "Добавить новый товар",
  "Edit Product Listing": "Редактировать товар",
  "Discard": "Отменить",
  "Save Product": "Сохранить товар",
  "Update Product": "Обновить товар",
  "Product Details": "Детали товара",
  "Product Name *": "Название товара *",
  "Category *": "Категория *",
  "Initial Stock *": "Начальный остаток *",
  "Current Stock *": "Текущий остаток *",
  "External Image URL (Optional)": "Внешний URL изображения (необязательно)",
  "Media Management": "Управление медиа",
  "Main Image": "Главное изображение",
  "Main Preview": "Предпросмотр главного фото",
  "Click or drag to upload primary image": "Нажмите или перетащите для загрузки главного изображения",
  "Gallery Images": "Галерея",
  "Loading product details...": "Загрузка деталей товара...",
  "Street Lamps": "Уличные светильники",
  "Landscape Lamps": "Ландшафтные светильники",
  "Ceiling Lights": "Потолочные светильники",
  "Wall Sconces": "Настенные бра",
  "Pendant Lamps": "Подвесные светильники",
  "Industrial Lighting": "Промышленное освещение",
  "e.g. Skyline Boulevard Street Lamp": "например, Уличный светильник Skyline Boulevard",
  "Detailed product specifications and features...": "Подробные технические характеристики и особенности товара...",
  "Please enter a valid stock level.": "Пожалуйста, введите корректное количество на складе.",
  "Product created successfully!": "Товар успешно создан!",
  "Failed to create product.": "Не удалось создать товар.",
  "Product updated successfully!": "Товар успешно обновлен!",
  "Failed to update product details.": "Не удалось обновить детали товара.",
  "Product details could not be found.": "Детали товара не найдены.",
  "Failed to load product details.": "Не удалось загрузить детали товара.",
  "Admin User Guide": "Руководство администратора",
  "Save as PDF": "Сохранить как PDF",
  "Step-by-step guidance for managing the website. This guide is publicly available and does not require an administrator login.": "Пошаговое руководство по управлению сайтом. Доступно без входа в систему.",
  "Getting Started": "Начало работы",
  "Navigation Guide": "Навигация",
  "Product Management": "Управление товарами",
  "Add a Product": "Добавление товара",
  "Update Stock": "Обновление остатков",
  "Upload Product Images": "Загрузка изображений товаров",
  "Order Management": "Управление заказами",
  "View Order Details": "Просмотр деталей заказа",
  "Update Order Status": "Изменение статуса заказа",
  "Customer Relationship Management": "Управление клиентами (CRM)",
  "CRM Dashboard": "Панель CRM",
  "Contacts and Companies": "Контакты и компании",
  "Sales Pipeline": "Воронка продаж",
  "Tasks and Activity History": "Задачи и история активности",
  "Customize the Homepage": "Настройка главной страницы",
  "Manage the Hero Slider": "Управление слайдером",
  "Upload Homepage Images": "Загрузка изображений главной страницы",
  "Configure Store Settings": "Настройка параметров магазина",
  "Customer Engagement": "Взаимодействие с клиентами",
  "Quote Requests": "Запросы КП",
  "Distributor Applications": "Заявки дистрибьюторов",
  "Contact Messages": "Сообщения с сайта",
  "Newsletter Subscribers": "Подписчики рассылки",
  "Account Management": "Управление аккаунтом",
  "Review revenue, orders, products, low-stock alerts, and recent activity from the Overview tab.": "Просматривайте выручку, заказы, товары, уведомления об остатках и активность на вкладке «Обзор».",
  "Use the sidebar to move between store management areas. On smaller screens, use the menu button to open it.": "Используйте боковое меню для перехода между разделами. На небольших экранах используйте кнопку меню.",
  "Open Products, select Add Product, complete the product details, upload images, then save it to the catalogue.": "Перейдите в «Товары», нажмите «Добавить товар», заполните данные, загрузите фото и сохраните.",
  "Find the product in Products, edit its stock quantity, and confirm the change. Low-stock alerts update automatically.": "Найдите товар в списке, измените остаток и подтвердите. Уведомления обновится автоматически.",
  "When adding or editing a product, upload JPG, PNG, or WebP files. The first image becomes the main product image.": "При добавлении или редактировании загружайте файлы JPG, PNG или WebP. Первое фото станет главным.",
  "Open Orders and select an order to see customer details, shipping information, items, and status.": "Перейдите в «Заказы» и выберите заказ, чтобы увидеть данные клиента, доставку, товары и статус.",
  "Expand an order and choose Pending, Processing, Shipped, Delivered, or Cancelled. The change saves automatically.": "Раскройте заказ и выберите статус: В ожидании, В обработке, Отправлен, Доставлен или Отменен.",
  "Open CRM from the left menu to review pipeline value, weighted forecast, won revenue, win rate, upcoming work, and recent customer activity.": "Откройте CRM в боковом меню для просмотра объема воронки, прогноза продаж, выручки и задач.",
  "Create complete contact and company profiles, assign lifecycle and lead statuses, score prospects, add tags, schedule follow-ups, and export filtered contacts to CSV.": "Создавайте профили контактов и компаний, задавайте статусы, оценки, теги и экспортируйте данные в CSV.",
  "Create revenue opportunities in Pipeline, assign contacts and companies, set value and closing dates, then move each deal through Lead, Qualified, Proposal, Negotiation, Won, or Lost.": "Создавайте сделки в воронке, связывайте с контактами, ведите сделки по этапам до успешного закрытия.",
  "Record notes, calls, emails, meetings, and tasks. Mark work complete and use the Overdue view to keep follow-ups from being missed.": "Записывайте заметки, звонки, письма, встречи и задачи. Отмечайте выполнение и отслеживайте просроченные дела.",
  "Use Website Content to update the hero, statistics, manufacturing section, and featured products, then save your changes.": "В разделе «Контент сайта» обновляйте слайдер, статистику, блок производства и товары.",
  "Use Website Content to add, remove, reorder, upload, or paste URLs for hero background slides. The homepage rotates them automatically and provides visitor controls.": "Управляйте фоновыми слайдами на главной странице: добавляйте, меняйте порядок и загружайте фото.",
  "Upload hero slider or manufacturing images, or enter direct image URLs. Check each preview before saving.": "Загружайте изображения для слайдера или блока производства либо вводите прямые ссылки.",
  "Use Settings to maintain store contact details, branding, social links, exchange rates, and wholesale minimum order quantity.": "В «Настройках» управляйте контактами магазина, брендингом, соцсетями, курсами валют и MOQ.",
  "Review requests in Quotes, open one for details, and update its status as the opportunity progresses.": "Просматривайте запросы в «Запросах цен», открывайте детали и обновляйте их статус.",
  "Review applicants in Distributors, check their business details, then mark each application as approved, rejected, or under review.": "Просматривайте заявки дистрибьюторов и меняйте их статус (Одобрено, Отклонено, На рассмотрении).",
  "Open Contacts to read customer messages and mark them as read after review.": "Открывайте сообщения клиентов и отмечайте их прочитанными.",
  "Manage active subscribers in Newsletter, add subscribers manually, and deactivate addresses when required.": "Управляйте подписчиками рассылки, добавляйте их вручную и отключайте при необходимости.",
  "Go to /login, enter an administrator email and password, then select Sign In.": "Перейдите на /login, введите email и пароль администратора, затем нажмите «Войти».",
  "Use the account area at the bottom of the admin sidebar and select Sign Out to end the session.": "Используйте блок аккаунта внизу бокового меню и нажмите «Выйти» для завершения сеанса.",
  "Need additional help?": "Нужна дополнительная помощь?",
  "Contact your site support team for help with anything not covered in this guide.": "Свяжитесь с поддержкой сайта по вопросам, не описанным в руководстве.",
  "Back to Dashboard": "Назад в панель",
  "Administration Manual": "Руководство по администрированию",
  "Last updated": "Последнее обновление",
  "Table of Contents": "Содержание",
  "Dashboard Overview": "Обзор панели",
  "Need Help?": "Нужна помощь?",
  "Contact the website development team if you encounter an issue that is not covered in this guide.": "Свяжитесь с командой разработки, если столкнулись с проблемой, не описанной в руководстве.",
  "Print / Save as PDF": "Печать / Сохранить как PDF",
  "Customer 360": "Обзор клиента 360°",
  "Customer relationships, sales follow-up, and forecasting in one workspace.": "Управление клиентами, продажами и прогнозированием в одном рабочем пространстве.",
  "Dashboard": "Панель управления",
  "Contacts": "Контакты",
  "Companies": "Компании",
  "Pipeline": "Воронка продаж",
  "Activities": "Активности",
  "Open pipeline": "Открытые сделки воронки",
  "Weighted forecast": "Взвешенный прогноз",
  "Average conversion": "Средняя конверсия",
  "Settled revenue": "Полученная выручка",
  "Settlement rate": "Уровень оплаты",
  "Pipeline health": "Здоровье воронки",
  "Next actions": "Следующие действия",
  "Add contact": "Добавить контакт",
  "Add activity": "Добавить активность",
  "Add deal": "Добавить сделку",
  "Search contacts...": "Поиск контактов...",
  "All owners": "Все ответственные",
  "All stages": "Все этапы",
  "Company": "Компания",
  "Owner": "Ответственный",
  "Next follow-up": "Следующий контакт",
  "Conversion": "Вероятность",
  "No contacts found": "Контакты не найдены",
  "New inquiry": "Новый запрос",
  "New inquiries": "Новые запросы",
  "Quoted Price": "Выставлен КП",
  "Negotiating price": "Согласование цены",
  "PI pending confirmation": "Ожидание подтверждения PI",
  "Deposit Received": "Получена предоплата",
  "Customs clearance and shipment": "Таможенное оформление и доставка",
  "Full payment settled": "Полная оплата произведена",
  "Contact details": "Детали контакта",
  "Contact name": "Имя контакта",
  "Source": "Источник",
  "Notes": "Заметки",
  "Deal value": "Сумма сделки",
  "Probability": "Вероятность",
  "Expected value": "Ожидаемая сумма",
  "Activity type": "Тип активности",
  "Due date": "Срок выполнения",
  "Completed": "Завершено",
  "Pending": "В ожидании",
  "Call": "Звонок",
  "Meeting": "Встреча",
  "Email follow-up": "Письмо",
  "Task": "Задача",
  "Analytics Overview": "Обзор аналитики",
  "Track website performance and visitor behavior.": "Отслеживание производительности сайта и поведения посетителей.",
  "7 Days": "7 дней",
  "30 Days": "30 дней",
  "90 Days": "90 дней",
  "Year to Date": "С начала года",
  "All Time": "За все время",
  "Visitors": "Посетители",
  "Page Views": "Просмотры страниц",
  "Sessions": "Сессии",
  "Bounce Rate": "Показатель отказов",
  "Avg. Session": "Ср. время сессии",
  "Traffic Overview": "Обзор трафика",
  "Top Pages": "Популярные страницы",
  "Traffic Sources": "Источники трафика",
  "Devices": "Устройства",
  "Browsers": "Браузеры",
  "Countries": "Страны",
  "Direct Navigation": "Прямые переходы",
  "Google Search": "Поиск Google",
  "Search Engines": "Поисковые системы",
  "Social Networks": "Социальные сети",
  "Desktop": "Компьютеры",
  "Mobile": "Мобильные",
  "Tablet": "Планшеты",
  "Other": "Другое",
  "No analytics data available for this period.": "Нет данных аналитики за этот период.",
  "Refresh": "Обновить",
  "View Site": "Перейти на сайт",
  "Loading data...": "Загрузка данных...",
  "Saved!": "Сохранено!",
  "from {count} orders": "из {count} заказов",
  "{count} pending": "{count} в ожидании",
  "{count} in stock": "{count} в наличии",
  "items below 5 units": "товаров менее 5 штук",
  "All": "Все",
  "Processing": "В обработке",
  "Shipped": "Отправлен",
  "Delivered": "Доставлен",
  "Cancelled": "Отменен",
  "Inactive": "Неактивен",
  "Unknown": "Неизвестно",
  "N/A": "Н/Д",
  "No quote requests yet": "Запросов цен пока нет",
  "No distributor applications yet": "Заявок дистрибьюторов пока нет",
  "No messages yet": "Сообщений пока нет",
  "{count} active": "{count} активных",
  "Export CSV": "Экспорт в CSV",
  "Add subscriber email...": "Email подписчика...",
  "Newsletter Subject": "Тема рассылки",
  "Email body content...": "Текст письма...",
  "Send via Email Client": "Отправить через почтовый клиент",
  "Opens your default email client with BCC to all active subscribers.": "Открывает ваш почтовый клиент по умолчанию с копией всем подписчикам.",
  "Analytics & Reports": "Аналитика и отчеты",
  "Stock update failed: {message}": "Ошибка обновления остатка: {message}",
  "Update failed: {message}": "Ошибка обновления: {message}",
  "Delete failed: {message}": "Ошибка удаления: {message}",
  "Failed: {message}": "Ошибка: {message}",
  "Delete this product?": "Удалить этот товар?",
  "Delete this order?": "Удалить этот заказ?",
  "Delete quote?": "Удалить этот запрос цены?",
  "Delete distributor application?": "Удалить заявку дистрибьютора?",
  "Delete message?": "Удалить это сообщение?",
  "Enter a valid email.": "Введите корректный email.",
  "Failed.": "Ошибка.",
  "Steps:": "Шаги:",
  "Need Additional Help?": "Нужна дополнительная помощь?",
  "Contact Support": "Связаться с поддержкой",
  "Step-by-step instructions for managing your Jinyu Capital website through the admin panel.": "Пошаговые инструкции по управлению сайтом Jinyu Capital через админ-панель.",
  "Failed to load dashboard data.": "Не удалось загрузить данные панели.",
  "Passwords do not match.": "Пароли не совпадают.",
  "Please fill in all required fields.": "Пожалуйста, заполните все обязательные поля.",
  "Blog post updated successfully!": "Запись в блоге успешно обновлена!",
  "Blog post created successfully!": "Запись в блоге успешно создана!",
  "Failed to save blog post.": "Не удалось сохранить запись в блоге.",
  "Are you sure you want to delete this blog post?": "Вы уверены, что хотите удалить эту запись?",
  "Edit what visitors see on the homepage.": "Редактирование содержимого главной страницы.",
  "Save All Changes": "Сохранить все изменения",
  "Slides rotate automatically every six seconds. Visitors can pause or navigate manually.": "Слайды меняются автоматически каждые 6 секунд.",
  "Add slide": "Добавить слайд",
  "Hero Sub-headline": "Подзаголовок главной страницы",
  "Hero slide {count} preview": "Предпросмотр слайда {count}",
  "Slide {count}": "Слайд {count}",
  "Move slide {count} left": "Переместить слайд {count} влево",
  "Move slide {count} right": "Переместить слайд {count} вправо",
  "Remove slide {count}": "Удалить слайд {count}",
  "Upload replacement image": "Загрузить новое изображение",
  "Section Headline": "Заголовок раздела",
  "Section Body Text": "Текст раздела",
  "Manufacturing Image URL": "URL изображения производства",
  "Or Upload Manufacturing Image": "Или загрузите изображение производства",
  "Click to upload image...": "Нажмите для загрузки...",
  "Manufacturing preview": "Предпросмотр блока производства",
  "Product {count}": "Товар {count}",
  "Or Upload New Image": "Или загрузите новое изображение",
  "Save Website Content": "Сохранить контент сайта",
  "Manage contact info, branding, and integrations.": "Управление контактами, брендингом и интеграциями.",
  "Save Settings": "Сохранить настройки",
  "Upload your company logo. Recommended: PNG with transparent background, min 200×200px.": "Загрузите логотип компании. Рекомендуется PNG с прозрачным фоном, от 200×200px.",
  "Full mailing address...": "Полный почтовый адрес...",
  "Facebook URL": "Ссылка на Facebook",
  "Instagram URL": "Ссылка на Instagram",
  "TikTok URL": "Ссылка на TikTok",
  "AUD Exchange Rate (1 USD =)": "Курс AUD (1 USD =)",
  "NGN Exchange Rate (1 USD =)": "Курс NGN (1 USD =)",
  "Global Wholesale MOQ": "Глобальный минимальный оптовый заказ (MOQ)",
  "Compose and publish articles to your website.": "Создавайте и публикуйте статьи на сайте.",
  "Title *": "Заголовок *",
  "Enter article title": "Введите заголовок статьи",
  "Slug (URL) *": "ЧПУ (URL) *",
  "Excerpt *": "Анонс *",
  "Brief summary of the article for listings (1-2 sentences)": "Краткая выжимка для списка статей (1-2 предложения)",
  "Upload a PNG, JPG, or WEBP image. Will be uploaded to Supabase Storage.": "Загрузите PNG, JPG или WEBP. Файл сохранится в Supabase Storage.",
  "Content (Supports Markdown) *": "Содержимое (поддерживается Markdown) *",
  "Write your article content here...": "Напишите текст статьи здесь...",
  "Update Post": "Обновить запись",
  "Publish Post": "Опубликовать запись",
  "Explosion-Proof Lighting": "Взрывозащищенное освещение",
  "Industrial Equipment": "Промышленное оборудование",
  "Industry News & Insights": "Новости и аналитика отрасли",
  "OEM/ODM Solutions": "Решения OEM/ODM",
  "Product Updates": "Обновления продуктов",
  "No articles found. Click \"New Post\" to create your first article!": "Статьи не найдены. Нажмите «Новая статья», чтобы создать первую!",
  "New administrators can sign in and manage the website immediately.": "Новые администраторы смогут сразу войти и управлять сайтом.",
  "Administrator name": "Имя администратора",
  "Email address": "Адрес эл. почты",
  "Use at least 12 characters. Share the temporary password securely.": "Используйте не менее 12 символов. Передавайте временный пароль надежным способом.",
  "Real-Time Traffic & User Analytics": "Аналитика трафика и пользователей в реальном времени",
  "Active website visitors, referring traffic links, country locales, device types, and sales revenue.": "Активные посетители, источники трафика, страны, устройства и выручка.",
  "YTD": "С начала года",
  "Export Report": "Экспорт отчета",
  "Active Users Now": "Активные пользователи сейчас",
  "Live visitors active in last 5 minutes": "Посетители за последние 5 минут",
  "15-Min Active Visitors": "Активные за 15 минут",
  "Unique session visitors in last 15 mins": "Уникальные посетители за 15 минут",
  "24-Hour Active Users": "Активные за 24 часа",
  "Unique user sessions recorded today": "Уникальные сессии за сегодня",
  "Traffic Sources & Referring Links": "Источники трафика и рефералы",
  "Origins and acquisition links of website traffic": "Источники и ссылки переходов",
  "{count} Pageviews": "{count} просмотров",
  "No referral traffic recorded in this timeframe yet.": "За этот период реферального трафика не зафиксировано.",
  "{count} views ({percent}%)": "{count} просмотров ({percent}%)",
  "Geographical Country Traffic": "География трафика по странам",
  "Global visitor locations & B2B distributor regions": "География посетителей и регионы дистрибьюторов",
  "No location traffic data recorded in this timeframe yet.": "За этот период гео-данные не зафиксированы.",
  "{count} interactions": "{count} взаимодействий",
  "Device Types & Browsers": "Устройства и браузеры",
  "Desktop vs Mobile vs Tablet ratio": "Соотношение ПК, мобильных и планшетов",
  "No device data": "Нет данных об устройствах",
  "Top Visited Pages & Content Traffic": "Популярные страницы и трафик",
  "Page URL paths with highest visitor traffic": "Страницы с наибольшим трафиком",
  "Page URL Path": "Путь к странице",
  "No page views recorded in this timeframe yet.": "За этот период просмотров страниц не зафиксировано.",
  "{count} views": "{count} просмотров",
  "Total Sales Revenue": "Общая выручка от продаж",
  "Based on {count} paid orders": "На основе {count} оплаченных заказов",
  "Average Order Value": "Средний чек",
  "Per transaction average": "Среднее значение за транзакцию",
  "Quote & Partner Leads": "Запросы цен и заявки партнеров",
  "{count} Inquiries": "{count} запросов",
  "{quotes} Quotes & {distributors} Distributor Apps": "{quotes} запросов цен и {distributors} заявок дистрибьюторов",
  "Catalog Products": "Товары в каталоге",
  "{count} Items": "{count} наименований",
  "Catalog Value: {value}": "Стоимость каталога: {value}",
  "Product Inventory & Stock Status": "Инвентарь и остатки товаров",
  "Real-time inventory levels from the products database table": "Остатки в реальном времени из базы данных",
  "Category:": "Категория:",
  "Product Name": "Название товара",
  "Unit Price": "Цена за unit",
  "Stock Quantity": "Количество на складе",
  "Catalog Valuation": "Оценка каталога",
  "No products found in database for the selected category.": "В выбранной категории товары не найдены.",
  "In Stock": "В наличии",
  "Out of Stock": "Нет в наличии",
  "Low Stock ({count})": "Мало на складе ({count})",
  "General": "Общее",
  "{count} units": "{count} шт.",
  "Showing top 10 of {count} products. Filter by category to view others.": "Показано 10 из {count} товаров. Отфильтруйте по категории.",
  "Direct / None": "Прямой запуск / Без источника",
  "Direct Locale": "Локальный переход",
  "Metric": "Метрика",
  "Timeframe": "Временной интервал",
  "Active Users (5 min)": "Активные (5 мин)",
  "Active Users (15 min)": "Активные (15 мин)",
  "Active Users (24 hours)": "Активные (24 часа)",
  "Total Page Views": "Всего просмотров страниц",
  "Valid/Paid Orders": "Оплаченные заказы",
  "Low Stock Alert Count": "Уведомления о низком остатке",
  "Out of Stock Count": "Количество отсутствующих товаров",
  "Close": "Закрыть",
  "Close dialog": "Закрыть диалог",
  "Close contact details": "Закрыть детали контакта",
  "Unassigned": "Не назначен",
  "Not set": "Не задано",
  "The CRM database migration has not been applied yet.": "Миграция БД CRM еще не применена.",
  "First name is required.": "Имя обязательно.",
  "Enter a valid email address.": "Введите корректный email.",
  "Contact updated.": "Контакт обновлен.",
  "Contact added.": "Контакт добавлен.",
  "Company name is required.": "Название компании обязательно.",
  "Company updated.": "Компания обновлена.",
  "Company added.": "Компания добавлена.",
  "Deal title is required.": "Название сделки обязательно.",
  "Deal updated.": "Сделка обновлена.",
  "Deal added to the pipeline.": "Сделка добавлена в воронку.",
  "Subject is required.": "Тема обязательна.",
  "Activity updated.": "Активность обновлена.",
  "Activity recorded.": "Активность записана.",
  "Moved to {stage}.": "Перемещено в stage «{stage}».",
  "Delete this {label}? This action cannot be undone.": "Удалить этот {label}? Это действие нельзя отменить.",
  "{label} deleted.": "{label} удален(а).",
  "contact": "контакт",
  "company": "компания",
  "deal": "сделка",
  "activity": "активность",
  "Loading your customer workspace...": "Загрузка рабочего пространства клиентов...",
  "CRM is ready to be activated": "CRM готова к активации",
  "Apply the included CRM database migration, then refresh this page. Existing orders, quotes, distributor applications, and messages will be organized automatically.": "Примените миграцию базы данных CRM и обновите страницу.",
  "Check again": "Проверить снова",
  "CRM data could not be loaded": "Не удалось загрузить данные CRM",
  "Try again": "Попробовать снова",
  "Customer relationships": "Взаимоотношения с клиентами",
  "One workspace for every relationship, deal, and follow-up.": "Единое пространство для управления клиентами, сделками и задачами.",
  "New deal": "Новая сделка",
  "New contact": "Новый контакт",
  "Refresh CRM": "Обновить CRM",
  "{count} overdue": "{count} просрочено",
  "{count} active deals": "{count} активных сделок",
  "Probability adjusted": "С учетом вероятности",
  "{count} customer records": "{count} записей клиентов",
  "{count} fully settled deals": "{count} полностью оплаченных сделок",
  "{count} closed deals": "{count} закрытых сделок",
  "Value, volume, and probability by conversion stage": "Сумма, объем и вероятность по этапам конверсии",
  "View pipeline": "Просмотр воронки",
  "{count} deals": "{count} сделок",
  "Add a deal to start forecasting your pipeline.": "Добавьте сделку для начала прогнозирования.",
  "Tasks and meetings that need attention": "Задачи и встречи, требующие внимания",
  "Complete {subject}": "Завершить «{subject}»",
  "No due date": "Без срока",
  "You are all caught up.": "Все задачи выполнены.",
  "Recent relationship activity": "Недавняя активность",
  "Latest notes, calls, emails, meetings, and tasks": "Последние заметки, звонки, письма, встречи и задачи",
  "View all": "Смотреть все",
  "No additional details": "Нет дополнительных деталей",
  "No activity has been recorded yet.": "Активность пока не записана.",
  "Search name, email, company, phone, or tag...": "Поиск по имени, email, компании, телефону или тегу...",
  "Filter by lifecycle stage": "Фильтр по жизненному циклу",
  "All lifecycle stages": "Все этапы жизненного цикла",
  "Filter by conversion stage": "Фильтр по этапам конверсии",
  "All conversion stages": "Все этапы конверсии",
  "Export filtered contacts": "Экспорт отфильтрованных контактов",
  "Contact": "Контакт",
  "Lifecycle": "Жизненный цикл",
  "Lead status": "Статус лида",
  "No contact details": "Нет контактных данных",
  "No title": "Без должности",
  "No contacts match your filters": "Нет контактов, соответствующих фильтрам",
  "Build your customer database": "Создайте базу клиентов",
  "Try a different search term, lifecycle stage, or conversion stage.": "Попробуйте другие условия поиска.",
  "Add the people your team sells to, supports, and partners with.": "Добавляйте контакты клиентов и партнеров.",
  "Add first contact": "Добавить первый контакт",
  "Search companies, industries, or locations...": "Поиск компаний, отраслей или местоположений...",
  "Add company": "Добавить компанию",
  "Industry not set": "Отрасль не указана",
  "Website": "Веб-сайт",
  "No companies match your search": "Компании не найдены",
  "Organize contacts by company": "Группировка контактов по компаниям",
  "Try a broader company, industry, or location search.": "Попробуйте расширить параметры поиска.",
  "Track accounts, partners, and prospects with their related contacts and opportunities.": "Отслеживайте компании, партнеров и сделки.",
  "Add first company": "Добавить первую компанию",
  "Sales pipeline": "Воронка продаж",
  "{open} open · {weighted} weighted forecast": "Открыто {open} · Взвешенный прогноз {weighted}",
  "{probability}% probability · {value}": "{probability}% вероятность · {value}",
  "High priority": "Высокий приоритет",
  "{probability}% · {value} weighted": "{probability}% · Взвешено {value}",
  "Move {title} to another stage": "Переместить «{title}» на другой этап",
  "No deals": "Нет сделок",
  "Open": "Открыто",
  "Overdue": "Просрочено",
  "All activity": "Вся активность",
  "Reopen activity": "Возобновить активность",
  "Complete activity": "Завершить активность",
  "General CRM activity": "Общая активность CRM",
  "Outcome:": "Результат:",
  "Nothing in this activity view": "В этом режиме нет активностей",
  "Record a note, call, email, meeting, or task to keep the relationship history complete.": "Запишите заметку, звонок, письмо, встречу или задачу.",
  "Edit contact": "Редактировать контакт",
  "Maintain a complete customer profile for sales and service.": "Поддерживайте актуальный профиль клиента.",
  "First name *": "Имя *",
  "Last name": "Фамилия",
  "Job title": "Должность",
  "No company": "Без компании",
  "Lifecycle stage": "Этап жизненного цикла",
  "Conversion stage": "Этап конверсии",
  "New inquiry (10%)": "Новый запрос (10%)",
  "Applied automatically when the contact is created.": "Применяется автоматически при создании контакта.",
  "Lead score / quality (0–100)": "Оценка лида / качество (0–100)",
  "Tags (comma separated)": "Теги (через запятую)",
  "Internal notes": "Внутренние заметки",
  "Contact has opted in to marketing communications": "Контакт согласился на маркетинговые рассылки",
  "Save changes": "Сохранить изменения",
  "Edit company": "Редактировать компанию",
  "Track an account, partner, or prospect organization.": "Отслеживание организации клиента или партнера.",
  "Company name *": "Название компании *",
  "Industry": "Отрасль",
  "Company size": "Размер компании",
  "Not specified": "Не указано",
  "Relationship": "Тип отношений",
  "City": "Город",
  "Address": "Адрес",
  "Edit deal": "Редактировать сделку",
  "Create and forecast a revenue opportunity.": "Создание и прогнозирование потенциальной выручки.",
  "Deal title *": "Название сделки *",
  "No contact": "Без контакта",
  "Expected close": "Ожидаемое закрытие",
  "Currency": "Валюта",
  "Used to weight this deal in the sales forecast.": "Используется для расчете взвешенного прогноза продаж.",
  "Priority": "Приоритет",
  "Loss reason": "Причина проигрыша",
  "Deal notes": "Заметки по сделке",
  "Edit activity": "Редактировать активность",
  "Keep the relationship timeline complete and actionable.": "Поддерживайте историю взаимодействия актуальной.",
  "Subject *": "Тема *",
  "Related deal": "Связанная сделка",
  "No deal": "Без сделки",
  "Details": "Детали",
  "Discussion notes, agenda, or task instructions...": "Заметки обсуждения, agenda или инструкции...",
  "Outcome": "Результат",
  "Optional result or next step": "Результат или следующий шаг (необязательно)",
  "Record activity": "Записать активность",
  "Quoted price": "Выставлен КП",
  "Deposit received": "Получена предоплата",
  "Lost / closed": "Проиграно / Закрыто",
  "Website enquiry received or contact added manually": "Запрос с сайта или добавлен вручную",
  "Quotation sent to the customer": "Коммерческое предложение отправлено клиенту",
  "Price and 40% deposit terms under negotiation": "Согласование цены и условий предоплаты 40%",
  "Proforma invoice awaiting customer confirmation": "Счет-проформа ожидает подтверждения",
  "Customer's 40% order deposit received": "Получена предоплата 40%",
  "Order in customs clearance or shipment": "Заказ на таможенном оформлении или в доставке",
  "Full order payment received and settled": "Полная оплата заказа получена",
  "Opportunity closed without conversion": "Сделка закрыта без конверсии",
  "Lead": "Лид",
  "Prospect": "Потенциальный клиент",
  "Opportunity": "Сделка",
  "Partner": "Партнер",
  "Attempted": "Попытка контакта",
  "Contacted": "Установлен контакт",
  "Qualified": "Квалифицирован",
  "Nurturing": "Взращивание",
  "Unqualified": "Не квалифицирован",
  "Manual": "Вручную",
  "Quote": "Запрос КП",
  "Order": "Заказ",
  "Distributor": "Дистрибьютор",
  "Import": "Импорт",
  "Referral": "Рекомендация",
  "Low": "Низкий",
  "Normal": "Обычный",
  "High": "Высокий",
  "Solo": "Индивидуальный",
  "Small": "Малый",
  "Medium": "Средний",
  "Large": "Крупный",
  "Enterprise": "Корпоративный",
  "Note": "Заметка",
  "Status Change": "Смена статуса",
  "Profile": "Профиль",
  "Not assigned": "Не назначен",
  "Lead score": "Оценка лида",
  "Tags": "Теги",
  "No tags": "Нет тегов",
  "Deals": "Сделки",
  "{count} opportunities": "{count} возможностей",
  "Add": "Добавить",
  "weighted": "взвешенный",
  "No deals linked to this contact.": "К этому контакту не привязаны сделки.",
  "Activity timeline": "История активности",
  "{count} recorded touchpoints": "{count} записанных взаимодействий",
  "No activity recorded for this contact yet.": "Для этого контакта пока нет записей о взаимодействии.",
};

const AdminLanguageContext = createContext<AdminLanguageContextValue | null>(null);

function subscribeToLanguage(callback: () => void) {
  window.addEventListener("storage", callback);
  window.addEventListener(LANGUAGE_CHANGE_EVENT, callback);
  return () => {
    window.removeEventListener("storage", callback);
    window.removeEventListener(LANGUAGE_CHANGE_EVENT, callback);
  };
}

function getLanguageSnapshot(): AdminLanguage {
  const saved = window.localStorage.getItem(STORAGE_KEY);
  return saved === "en" || saved === "zh" || saved === "ru" ? saved : "zh";
}

function getServerLanguageSnapshot(): AdminLanguage {
  return "zh";
}

function interpolate(message: string, values?: TranslationValues) {
  if (!values) return message;
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    message,
  );
}

export function AdminLanguageProvider({ children }: { children: React.ReactNode }) {
  // The server snapshot is deliberately Chinese. React then synchronizes any
  // saved browser preference after hydration without an English server flash.
  const language = useSyncExternalStore(
    subscribeToLanguage,
    getLanguageSnapshot,
    getServerLanguageSnapshot,
  );

  useEffect(() => {
    const previousLanguage = document.documentElement.lang;
    document.documentElement.lang = language === "zh" ? "zh-CN" : language === "ru" ? "ru" : "en";
    return () => {
      document.documentElement.lang = previousLanguage;
    };
  }, [language]);

  const setLanguage = useCallback((nextLanguage: AdminLanguage) => {
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT));
  }, []);

  const t = useCallback(
    (message: string, values?: TranslationValues) => {
      const translated =
        language === "zh"
          ? zh[message] ?? message
          : language === "ru"
            ? ru[message] ?? message
            : message;
      return interpolate(translated, values);
    },
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <AdminLanguageContext.Provider value={value}>
      {children}
      <div className="fixed bottom-4 left-4 z-[100] flex items-center gap-2 rounded-xl border bg-background/95 px-3 py-2 shadow-lg backdrop-blur print:hidden">
        <Languages className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
        <label htmlFor="admin-language" className="sr-only">{t("Language")}</label>
        <select
          id="admin-language"
          value={language}
          onChange={(event) => setLanguage(event.target.value as AdminLanguage)}
          className="bg-transparent text-sm font-medium outline-none"
          aria-label={t("Language")}
        >
          <option value="zh">中文</option>
          <option value="en">English</option>
          <option value="ru">Русский</option>
        </select>
      </div>
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  if (!context) throw new Error("useAdminLanguage must be used inside AdminLanguageProvider");
  return context;
}
