"use client";

import React, { createContext, useCallback, useContext, useEffect, useMemo, useSyncExternalStore } from "react";

export type WebsiteLanguage = "en" | "zh" | "ru" | "fr";

type TranslationValues = Record<string, string | number>;

type WebsiteLanguageContextValue = {
  language: WebsiteLanguage;
  setLanguage: (language: WebsiteLanguage) => void;
  t: (message: string, values?: TranslationValues) => string;
};

const STORAGE_KEY = "jinyu_website_language";
const LANGUAGE_CHANGE_EVENT = "jinyu-website-language-change";

// Chinese Dictionary
const zh: Record<string, string> = {
  // Navigation & General
  "Home": "首页",
  "About": "关于我们",
  "Products": "产品中心",
  "Blog": "新闻动态",
  "Distributor": "经销商",
  "Contact": "联系我们",
  "Request a quote": "索取报价",
  "Request a Quote": "索取报价",
  "Explore products": "浏览产品",
  "Contact sales": "联系销售",
  "Contact our sales team": "联系销售团队",
  "Quick links": "快速链接",
  "Follow us": "关注我们",
  "Language": "语言",
  "Chinese": "中文",
  "English": "English",
  "Russian": "Русский",
  "French": "Français",
  "Quote": "报价",
  "Our Story": "关于我们",
  "Cart": "购物车",

  // Hero & Brand
  "Manufacturing Excellence From China To The World": "精益制造 始于中国 服务全球",
  "Jinyu combines manufacturing, OEM production, product development, and global supply chain solutions for distributors, wholesalers, contractors, and brands worldwide.": "Jinyu 融合了制造、OEM 生产、产品研发及全球供应链解决方案，服务于全球经销商、批发商、工程商和品牌商。",
  "Your trusted manufacturer of premium lighting equipment and appliances, delivering engineering excellence and quality since 2018.": "您值得信赖的高端照明设备与电器制造商，自 2018 年起致力于卓越工程与品质。",
  "Looking to expand your business?": "想要拓展您的业务？",
  "Become a Distributor": "成为经销商",
  "Become a Global Distributor": "成为全球经销商",
  "Explore Catalogue": "浏览产品目录",
  "Apply Now": "立即申请",
  "All rights reserved.": "保留所有权利。",
  "Website design by SpaceMinds": "网站设计 SpaceMinds",
  "Privacy Policy": "隐私政策",
  "Terms of Service": "服务条款",

  // Stats
  "Product lines": "产品线系列",
  "Sq.m facility": "平方米生产基地",
  "Countries exported": "出口国家与地区",
  "9001 Certified": "9001 质量认证体系",

  // Manufacturing Section
  "Manufacturing Excellence": "精益制造实力",
  "Manufacturing excellence": "精益制造实力",
  "Built on a foundation of engineering expertise, we deliver reliable products that meet the demands of global markets. Our Guangzhou facility represents the pinnacle of modern production capabilities.": "依托深厚的工程技术积累，我们制造符合全球市场需求的高品质产品。广州生产基地代表了现代制造业的顶尖能力。",
  "Advanced manufacturing": "先进制造体系",
  "State-of-the-art production facilities equipped with automated assembly lines for precision and scale.": "拥有先进的自动化生产线和精密的装配流水线，保障精度与规模化交付。",
  "Rigorous quality control": "严苛质量管控",
  "Comprehensive testing protocols ensuring every appliance and lighting fixture meets international safety standards.": "完善的全流程检测机制，确保每一套照明器具均符合国际安全标准。",
  "Innovative engineering": "前沿工程研发",
  "Dedicated R&D team continuously developing energy-efficient and smart technology solutions.": "专业的研发团队持续开发高效节能与智能化技术解决方案。",
  "Guangzhou Production Facility": "广州生产制造基地",
  "High-performance manufacturing, assembly, and testing workshop": "高性能生产、装配与检测车间",
  "Sq.m Production Area": "平方米生产厂房面积",

  // Showcase Products
  "Featured Product Lines": "精选产品系列",
  "Featured product lines": "精选产品系列",
  "Explore our signature street lighting collections, engineered for superior outdoor performance, longevity, and aesthetic appeal.": "探索我们的标志性路灯与照明系列，兼具卓越户外性能、超长寿命与现代美学设计。",
  "View all products": "查看所有产品",
  "Skyline Boulevard Series": "天际大道系列",
  "Designed for modern cities, business districts, residential communities, and municipal infrastructure projects, the Skyline Boulevard Series combines contemporary aesthetics with exceptional lighting performance. Its durable construction, energy-efficient LED technology, and weather-resistant design ensure reliable illumination while enhancing the appearance of any roadway.": "天际大道系列专为现代城市、中央商务区、高端社区和市政基础设施项目设计，将现代美学与卓越照明性能完美结合。坚固耐用的结构、高效节能的 LED 技术以及耐候防护设计，在提升道路美观度的同时确保长效稳定照明。",
  "Urban Road Lighting Series": "城市道路照明系列",
  "Reliable LED street lighting for urban roads, parks, estates, and commercial projects. Designed for strong illumination, energy efficiency, and long service life.": "专为城市道路、公园绿地、产业园区及商业项目打造的可靠 LED 路灯，具备高照度、节能降耗和超长使用寿命。",
  "Metro Avenue Series": "都市干道系列",
  "Modern LED street lighting for highways, city roads, business parks, and residential developments. Built for efficient illumination, durability, and long-lasting outdoor performance.": "适用于高速公路、城市干道、商业园区及住宅小区的现代 LED 路灯，专为高效照明、耐用性与持久户外性能打造。",

  // Product Catalog
  "Product Portfolio": "产品系列全览",
  "Browse our focused range of high-performance municipal and commercial lighting solutions, engineered for precision, durability, and contemporary aesthetics.": "浏览我们专为市政和商业照明打造的高性能解决方案，兼具精密工程、耐用性与现代美感。",
  "All Categories": "所有类别",
  "All Products": "所有产品",
  "Street Lamps": "路灯",
  "Landscape Lamps": "景观灯",
  "Ceiling Lights": "吸顶灯",
  "Wall Sconces": "壁灯",
  "Pendant Lamps": "吊灯",
  "Industrial Lighting": "工业照明",
  "Explosion-Proof Lighting": "防爆照明",
  "Street Lighting": "路灯照明",
  "Landscape Lighting": "景观照明",
  "Commercial & Industrial Lighting": "商业与工业照明",
  "Landscape & Urban Lamps": "景观与市政路灯",
  "OEM / ODM Custom Manufacturing": "OEM / ODM 定制制造",
  "Search products...": "搜索产品...",
  "Sort by": "排序方式",
  "Featured": "精选推荐",
  "Price: Low to High": "价格：从低到高",
  "Price: High to Low": "价格：从高到低",
  "View Details": "查看详情",
  "Add to Cart": "加入购物车",
  "In Stock": "有现货",
  "Out of Stock": "暂无现货",
  "Minimum Order:": "最小起订量：",
  "In stock and ready to ship worldwide": "有现货，支持全球快速发货",
  "Back to Products": "返回产品列表",
  "Go back": "返回上一页",
  "Product not found": "未找到该产品",
  "Specifications": "规格参数",
  "Quantity": "数量",
  "No products found": "未找到相关产品",
  "We couldn't find any products in this category. Please try another category.": "在该类别下未找到任何产品，请尝试选择其他类别。",

  // Product Names & Descriptions
  "Jinyu Skyline Boulevard LED Street Lamp": "Jinyu 天际大道系列 LED 路灯",
  "100W-250W high-output street lamp engineered with a die-cast aluminum housing and IP66 waterproof rating for high-performance municipal, highway, and parking lot illumination.": "100W-250W 高光效路灯，采用压铸铝外壳与 IP66 防水等级，专为市政道路、高速公路及停车场照明设计。",
  "Jinyu Metro Avenue LED Street Lamp": "Jinyu 都市干道系列 LED 路灯",
  "80W-200W premium street luminaire designed for highways and urban avenues. Heavy-duty aluminum alloy housing with advanced thermal management.": "80W-200W 高端路灯，适用于高速公路与城市主干道，采用高强度铝合金外壳及先进散热设计。",
  "Jinyu Fortune Tree Landscape Lamp": "Jinyu 发财树景观灯",
  "4.0m-6.0m elegant outdoor tree luminaire constructed from galvanized steel and aluminum. Perfect for parks, public plazas, and luxury commercial walkways.": "4.0m-6.0m 典雅户外树形灯具，采用镀锌钢与铝材精制，适用于公园、公共广场及高端商业步道。",
  "Jinyu Van Gogh Trees Landscape Lamp": "Jinyu 梵高之树艺术景观灯",
  "3.5m-5.5m artistic tree structure featuring die-cast aluminum alloy canopy and leaves. Integrates RGB ambient lighting for premium nightscape designs.": "3.5m-5.5m 艺术树形结构，采用压铸铝合金树冠与叶片，集成 RGB 氛围照明，打造高端夜景。",
  "Jinyu Angel's Wings Landscape Light": "Jinyu 天使之翼造型景观灯",
  "4.5m tall modern landscape sculpture made of premium grade 304 stainless steel. Features a swept-back illuminated form silhouette providing ambient night glow.": "4.5m 高现代景观雕塑灯，采用 304 不锈钢精制，流线后掠发光轮廓，营造柔美夜间光影。",
  "Jinyu Smart Ceiling Light": "Jinyu 智能吸顶灯",
  "Sleek, low-profile intelligent ceiling lamp. Features customizable color temperatures (3000K-6000K), voice assistant compatibility, and high energy efficiency.": "纤薄低调的智能吸顶灯，支持色温调节（3000K-6000K）、语音助手控制，具备高效节能特性。",
  "Jinyu Luxury Acrylic Panel Light": "Jinyu 轻奢亚克力平板灯",
  "Contemporary square ceiling panel light with a high-transmittance luxury acrylic diffuser. Provides glare-free, uniform light for modern office and residential spaces.": "现代方形吸顶平板灯，采用高透光轻奢亚克力扩散板，为办公及家居空间提供无眩光均匀光照。",
  "Jinyu Electroplated Wall Lamp": "Jinyu 电镀工艺轻奢壁灯",
  "Elegant modern wall sconce with a hand-polished electroplated finish. Delivers a soft warm white glow ideal for luxury hallways and dining spaces.": "典雅现代壁灯，采用手工抛光电镀工艺，散发柔和暖白光，适用于高端走廊与餐厅空间。",
  "Jinyu Walnut Finish Tri-Color LED Pendant": "Jinyu 胡桃木纹三色温 LED 吊灯",
  "Minimalistic linear pendant lamp in solid walnut wood finish. Features tri-color LED switching (warm, neutral, cool white) for customizable dining experiences.": "极简线条吊灯，胡桃木纹质感，具备三色温切换（暖光/中性光/冷白光），打造舒适就餐氛围。",
  "Jinyu Heavy Duty Industrial Floodlight": "Jinyu 重型工业投光灯",
  "High-output industrial LED floodlight built for sports arenas, ports, and construction sites. Features robust IP66 weatherproofing and die-cast aluminum heat sink.": "高输出工业 LED 投光灯，适用于体育场馆、港口码头及建筑工地，具备坚固的 IP66 防水及压铸铝散热器。",

  // Specification Keys & Values
  "Wattage": "功率",
  "Input Voltage": "输入电压",
  "Color Temperature": "色温",
  "IP Rating": "防护等级",
  "Material": "材质",
  "Lifespan": "使用寿命",
  "Warranty": "质保期",
  "Certifications": "认证标准",
  "Beam Angle": "光束角",
  "Luminous Flux": "光通量",

  // About Page
  "About Jinyu Capital": "关于 Jinyu Capital",
  "Leading Manufacturer of Industrial & Architectural Lighting": "领先的工业与建筑照明制造商",
  "Established in 2018 in Guangzhou, Jinyu Capital specialized in high-grade LED fixtures, explosion-proof luminaires, and specialized outdoor lighting systems.": "Jinyu Capital 于 2018 年成立于广州，专注于高等级 LED 灯具、防爆灯具及专业户外照明系统。",
  "Engineering Innovation Industrial Reliability": "工程创新 工业品质 值得信赖",
  "Jinyu specializes in the design, manufacturing, and supply of explosion-proof lighting and industrial electrical solutions for global markets": "Jinyu 专注于面向全球市场设计、制造及供应防爆灯具与工业电气解决方案。",
  "Our story": "发展历程",
  "Driven by innovation and quality, Jinyu has developed a complete manufacturing ecosystem covering mold development, die-casting, production, assembly, and OEM/ODM customization.": "在创新与品质驱动下，Jinyu 已建立涵盖模具开发、压铸、生产、组装及 OEM/ODM 定制的完整制造生态系统。",
  "Annual production exceeds 2.4 million units, supported by advanced facilities, experienced engineering teams, and strict quality control systems.": "年产量超过 240 万套，依托先进设施、经验丰富的工程团队与严苛的质量管控体系。",
  "Backed by 80+ patents and international certifications including ISO, CCC, EX, and ATEX, we deliver reliable solutions for industrial and hazardous environments worldwide.": "拥有 80 多项专利及 ISO、CCC、EX、ATEX 等国际认证，为全球工业及危险环境提供可靠解决方案。",
  "Our Core Values": "核心价值观",
  "The principles that guide our manufacturing processes and client relationships.": "指导我们制造流程与客户关系的核心准则。",
  "Precision": "精益求精",
  "We maintain strict tolerances and rigorous quality control in every stage of our manufacturing process.": "我们在生产制造的每个阶段都保持严格的公差与严苛的质量把控。",
  "Innovation": "持续创新",
  "We continuously invest in R&D to develop energy-efficient lighting and smarter, more durable appliances.": "我们持续加大研发投入，开发高效节能的照明产品和更智能耐用的电器设备。",
  "Partnership": "合作共赢",
  "We build lasting relationships with our global distributors through transparency and consistent delivery.": "我们通过透明沟通和稳定交付，与全球经销商建立长久稳固的合作关系。",
  "Our Mission": "我们的使命",
  "Quality Assurance": "质量保证",
  "R&D Innovation": "研发创新",
  "Global Presence": "全球化布局",

  // Contact Page & Company Address
  "Contact Us": "联系我们",
  "Get in touch": "联系我们",
  "Get in Touch": "保持联系",
  "Have questions about our platform or services? Our team is here to help you get started with professional trading.": "对我们的产品与服务有任何疑问？我们的团队随时为您解答并提供专业支持。",
  "We're here to answer your questions, assist with custom OEM/ODM requests, and support your project requirements.": "我们随时解答您的疑问，协助处理 OEM/ODM 定制需求，并为您的项目提供支持。",
  "Send us a message": "给我们留言",
  "Contact information": "联系方式",
  "Office": "公司地址",
  "Support hours": "工作时间",
  "Email": "电子邮箱",
  "Phone": "联系电话",
  "Monday - Friday, 8:00 AM - 6:00 PM EST": "周一至周五，上午 8:00 - 下午 6:00 (EST)",
  "Unit 119, Building 19, Changfeng International, No. 96 Lixin 12th Road, Xintang Town, Zengcheng District, Guangzhou City": "中国广东省广州市增城区新塘镇利新十二路96号长风国际19栋119单元",
  "No. 119, Building 19, Changfeng International, 96 Li Xin No. 12 Road, Xin Tang Town, Zengcheng District, Guangzhou City": "中国广东省广州市增城区新塘镇利新十二路96号长风国际19栋119单元",
  "Need immediate assistance?": "需要紧急协助？",
  "Our support team is available during business hours to help with account setup, platform questions, and technical issues.": "我们的客服与工程团队在工作时间内随时为您解答产品与技术疑问。",
  "Full Name": "姓名",
  "Email Address": "电子邮箱",
  "Phone Number": "电话号码",
  "Company Name": "公司名称",
  "Project Type / Details": "项目类型 / 详细说明",
  "Send Message": "发送留言",
  "Your full name": "您的全名",
  "your.email@example.com": "your.email@example.com",
  "Your company name": "您的公司名称",
  "Tell us more about your inquiry...": "请详细描述您的咨询或项目需求...",
  "Name is required": "请填写姓名",
  "Email is required": "请填写电子邮箱",
  "Please enter a valid email address": "请输入有效的电子邮箱地址",
  "Message is required": "请填写留言内容",
  "Message must be at least 10 characters": "留言内容至少需要 10 个字符",
  "Message sent successfully. Our sales team will contact you shortly.": "留言发送成功！我们的销售团队将尽快与您联系。",
  "Failed to send message. Please try again.": "发送失败，请稍后重试。",
  "Thank you for reaching out! We will reply within 24 hours.": "感谢您的联系！我们将在 24 小时内回复。",

  // Distributor Page & Form
  "Partner with Jinyu Capital to bring high-quality, innovative lighting and appliance solutions to your local market. Fill out the application below to start the conversation.": "与 Jinyu Capital 合作，将优质创新的照明与电器解决方案引入您的本地市场。填写下方申请表即可开始对话。",
  "Join our global network of authorized regional distributors and partners.": "加入我们的全球授权区域经销商与合作伙伴网络。",
  "Company Information": "公司基本信息",
  "Company Name *": "公司名称 *",
  "Country / Region *": "国家 / 地区 *",
  "Business Type *": "业务类型 *",
  "Select business type": "选择业务类型",
  "Wholesaler": "批发采购商",
  "Contractor": "工程承包商",
  "Brand": "品牌合作商",
  "Other": "其他类型",
  "Contact Details": "联系人信息",
  "Contact Person *": "联系人姓名 *",
  "Full name": "姓名全称",
  "Email Address *": "电子邮箱 *",
  "Phone Number *": "联系电话 *",
  "Business Profile": "业务概况与资质",
  "Current Business Experience": "现有业务经验与经营情况",
  "Briefly describe your current operations, years in business, and market reach...": "简要介绍您的现有业务运营、从业年限及市场覆盖范围...",
  "Product Categories of Interest": "意向经销产品系列",
  "Which Jinyu product lines are you most interested in distributing?": "您最有兴趣经销哪些 Jinyu 产品系列？",
  "Additional Information": "补充说明信息",
  "Any other details you'd like to share with our team...": "您希望与我们团队分享的其他详细信息...",
  "Submit Application": "提交经销商申请",
  "Submitting Application...": "正在提交申请...",
  "Application submitted successfully. Our team will review and contact you shortly.": "申请提交成功！我们的渠道拓展团队将审核并尽快与您联系。",
  "Please fill in all required fields correctly.": "请正确填写所有必填项。",
  "Company name is required": "请填写公司名称",
  "Contact person is required": "请填写联系人",
  "Country/Region is required": "请填写国家/地区",
  "Business type is required": "请选择业务类型",
  "Phone number is required": "请填写联系电话",
  "e.g. Global Lighting Corp": "例如：全球照明工程有限公司",
  "e.g. United States": "例如：中国 / 美国 / 俄罗斯",
  "work@company.com": "work@company.com",

  // Request a Quote Page
  "B2B & Commercial Inquiry": "B2B 与商业工程询价",
  "Request a Project Quote": "索取项目定制报价",
  "Submit your architectural, street, or landscape lighting requirements below. Our engineering and sales team will review your specifications and provide a competitive wholesale quote.": "请在下方提交您的建筑、市政路灯或景观照明项目需求。我们的工程与销售团队将审核您的技术规范并提供具有竞争力的批发报价。",
  "Quote Request Received": "已收到您的报价申请",
  "Thank you for submitting your project specifications. Our sales engineers are reviewing your request and will contact you within 24 business hours.": "感谢您提交项目技术规格！我们的销售工程师正在审核您的需求，并将于 24 小时内与您联系。",
  "Submit another quote request": "提交另一份报价申请",
  "First Name *": "名 *",
  "Last Name *": "姓 *",
  "Project Type *": "项目类型 *",
  "Street & Highway Lighting": "市政道路与高速公路照明",
  "Landscape & Architectural": "景观与建筑亮化",
  "Industrial Floodlights": "工业投光灯与特种照明",
  "Custom OEM/ODM Manufacturing": "定制 OEM / ODM 制造",
  "Product of Interest": "感兴趣的产品型号",
  "Est. Quantity *": "预估采购数量 *",
  "Project Specifications & Details *": "项目技术参数与详细要求 *",
  "Describe your project, required certifications (CE, RoHS, UL), voltage specs, and any customization requests...": "请详细描述您的项目背景、所需认证（CE、RoHS、ATEX等）、电压规格及任何定制化需求...",
  "SUBMIT QUOTE REQUEST": "提交报价申请",
  "SENDING REQUEST...": "正在发送申请...",
  "Engineering Standards": "工程技术标准",
  "Jinyu Capital operates state-of-the-art aluminum die-casting, automated SMT lines, and photometric testing labs to ensure pro-grade durability.": "Jinyu Capital 拥有先进的铝合金压铸车间、全自动 SMT 贴片线及光学检测实验室，确保专业级耐用性。",
  "Commercial Warranty": "商业项目质保",
  "Every commercial lighting product includes a 5-year replacement warranty, full certificate compliance support, and free local shipping coordination.": "每套商用照明产品均享有多达 5 年换新质保、全套合规认证支持以及贴心的物流调度服务。",
  "24-Hour Turnaround": "24 小时极速响应",
  "Our sales engineers review photometrics files, BOM requirements, and logistics paths to deliver accurate quote sheets within 1 business day.": "我们的销售工程师会审核光学文件、BOM 清单及物流方案，在 1 个工作日内提供准确的报价单。",
  "Need Assistance?": "需要即时协助？",
  "For custom OEM molds or general questions about supply chain scheduling, email our support directly at": "有关定制 OEM 模具或供应链排期的咨询，请直接发邮件至",

  // CTA & Blog
  "Partner with a reliable manufacturer": "与值得信赖的源头制造厂商合作",
  "Whether you need OEM services or bulk orders of our standard product lines, our team is ready to support your business.": "无论您需要 OEM 定制服务还是标准产品的大批量采购，我们的专业团队都随时为您提供全方位支持。",
  "Latest news & insights": "最新行业动态与技术资讯",
  "Stay updated with our latest technology breakthroughs, lighting guides, and company announcements.": "了解我们在照明技术突破、行业应用指南及企业动态方面的最新资讯。",
  "Read all insights": "阅读全部资讯",
  "Read More →": "阅读全文 →",
  "Industry Insights & News": "行业洞察与新闻动态",
  "Stay informed with the latest trends in industrial manufacturing, explosion-proof technology, and robust engineering solutions.": "掌握工业制造、防爆技术和高耐久工程解决方案的最新趋势。",
  "All": "全部",
  "Industrial Equipment": "工业设备",
  "Industry News & Insights": "行业动态与观点",
  "OEM/ODM Solutions": "OEM/ODM 解决方案",
  "Product Updates": "产品更新",
  "No articles found": "未找到相关文章",
  "No articles match your current filters or search terms.": "没有与您当前筛选条件或搜索关键词匹配的文章。",
  "Clear Filters": "清除筛选条件",
  "Loading article...": "正在加载文章...",
  "Article Not Found": "未找到该文章",
  "The article you are looking for does not exist or may have been moved.": "您查找的文章不存在或已被移除。",
  "Back to Blog": "返回新闻博客",
  "Back": "返回",
  "By": "作者：",
};

// Russian Dictionary
const ru: Record<string, string> = {
  // Navigation & General
  "Home": "Главная",
  "About": "О нас",
  "Products": "Продукция",
  "Blog": "Блог",
  "Distributor": "Дистрибьюторам",
  "Contact": "Контакты",
  "Request a quote": "Запросить КП",
  "Request a Quote": "Запросить КП",
  "Explore products": "Каталог продукции",
  "Contact sales": "Связаться с нами",
  "Contact our sales team": "Связаться с отделом продаж",
  "Quick links": "Быстрые ссылки",
  "Follow us": "Мы в соцсетях",
  "Language": "Язык",
  "Chinese": "中文",
  "English": "English",
  "Russian": "Русский",
  "French": "Français",
  "Quote": "Запрос КП",
  "Our Story": "О нас",
  "Cart": "Корзина",

  // Hero & Brand
  "Manufacturing Excellence From China To The World": "Производственное совершенство из Китая по всему миру",
  "Jinyu combines manufacturing, OEM production, product development, and global supply chain solutions for distributors, wholesalers, contractors, and brands worldwide.": "Jinyu объединяет производство, выпуск продукции OEM, разработку и глобальные цепочки поставок для дистрибьюторов и оптовиков.",
  "Your trusted manufacturer of premium lighting equipment and appliances, delivering engineering excellence and quality since 2018.": "Ваш надежный производитель осветительного оборудования премиум-класса с 2018 года.",
  "Looking to expand your business?": "Хотите расширить свой бизнес?",
  "Become a Distributor": "Стать дистрибьютором",
  "Become a Global Distributor": "Стать мировым дистрибьютором",
  "Explore Catalogue": "Смотреть каталог",
  "Apply Now": "Подать заявку",
  "All rights reserved.": "Все права защищены.",
  "Website design by SpaceMinds": "Дизайн сайта SpaceMinds",
  "Privacy Policy": "Политика конфиденциальности",
  "Terms of Service": "Условия обслуживания",

  // Stats
  "Product lines": "Линейки продукции",
  "Sq.m facility": "кв.м производственных площадей",
  "Countries exported": "Стран экспорта",
  "9001 Certified": "Сертификат ISO 9001",

  // Manufacturing Section
  "Manufacturing Excellence": "Производственное совершенство",
  "Manufacturing excellence": "Производственное совершенство",
  "Built on a foundation of engineering expertise, we deliver reliable products that meet the demands of global markets. Our Guangzhou facility represents the pinnacle of modern production capabilities.": "Опираясь на глубокий инженерный опыт, мы создаем надежную продукцию, отвечающую требованиям мировых рынков. Наш завод в Гуанчжоу оснащен передовым оборудованием.",
  "Advanced manufacturing": "Передовое производство",
  "State-of-the-art production facilities equipped with automated assembly lines for precision and scale.": "Современные производственные мощности с автоматизированными линиями сборки для точности и масштабируемости.",
  "Rigorous quality control": "Строгий контроль качества",
  "Comprehensive testing protocols ensuring every appliance and lighting fixture meets international safety standards.": "Комплексные протоколы тестирования гарантируют соответствие каждого светильника международным стандартам безопасности.",
  "Innovative engineering": "Инновационные разработки",
  "Dedicated R&D team continuously developing energy-efficient and smart technology solutions.": "Специализированная команда R&D непрерывно разрабатывает энергоэффективные и интеллектуальные решения.",
  "Guangzhou Production Facility": "Производственный комплекс в Гуанчжоу",
  "High-performance manufacturing, assembly, and testing workshop": "Цех высокоточного производства, сборки и тестирования",
  "Sq.m Production Area": "кв.м производственной площади",

  // Showcase Products
  "Featured Product Lines": "Популярные линейки продукции",
  "Featured product lines": "Популярные линейки продукции",
  "Explore our signature street lighting collections, engineered for superior outdoor performance, longevity, and aesthetic appeal.": "Ознакомьтесь с нашими флагманскими коллекциями уличного освещения с превосходной надежностью и дизайном.",
  "View all products": "Все товары",
  "Skyline Boulevard Series": "Серия Skyline Boulevard",
  "Designed for modern cities, business districts, residential communities, and municipal infrastructure projects, the Skyline Boulevard Series combines contemporary aesthetics with exceptional lighting performance. Its durable construction, energy-efficient LED technology, and weather-resistant design ensure reliable illumination while enhancing the appearance of any roadway.": "Серия Skyline Boulevard создана для современных городов, деловых кварталов и муниципальных проектов. Сочетает эстетику, надежную конструкцию, энергоэффективные LED-модули и защиту от непогоды.",
  "Urban Road Lighting Series": "Серия Urban Road Lighting",
  "Reliable LED street lighting for urban roads, parks, estates, and commercial projects. Designed for strong illumination, energy efficiency, and long service life.": "Надежное уличное светодиодное освещение для городских дорог, парков и коммерческих объектов. Высокая яркость, экономичность и долгий срок службы.",
  "Metro Avenue Series": "Серия Metro Avenue",
  "Modern LED street lighting for highways, city roads, business parks, and residential developments. Built for efficient illumination, durability, and long-lasting outdoor performance.": "Современное светодиодное освещение для шоссе, городских магистралей и технопарков. Создано для максимальной долговечности и эффективности.",

  // Product Catalog
  "Product Portfolio": "Каталог продукции",
  "Browse our focused range of high-performance municipal and commercial lighting solutions, engineered for precision, durability, and contemporary aesthetics.": "Ознакомьтесь с нашим ассортиментом надежных решений для муниципального и коммерческого освещения.",
  "All Categories": "Все категории",
  "All Products": "Все товары",
  "Street Lamps": "Уличные светильники",
  "Landscape Lamps": "Ландшафтные светильники",
  "Ceiling Lights": "Потолочные светильники",
  "Wall Sconces": "Настенные бра",
  "Pendant Lamps": "Подвесные светильники",
  "Industrial Lighting": "Промышленное освещение",
  "Explosion-Proof Lighting": "Взрывозащищенное освещение",
  "Street Lighting": "Уличное освещение",
  "Landscape Lighting": "Ландшафтное освещение",
  "Commercial & Industrial Lighting": "Коммерческое и промышленное освещение",
  "Landscape & Urban Lamps": "Ландшафтное и уличное освещение",
  "OEM / ODM Custom Manufacturing": "Контрактное производство OEM / ODM",
  "Search products...": "Поиск товаров...",
  "Sort by": "Сортировка",
  "Featured": "Популярные",
  "Price: Low to High": "Цена: по возрастанию",
  "Price: High to Low": "Цена: по убыванию",
  "View Details": "Подробнее",
  "Add to Cart": "В корзину",
  "In Stock": "В наличии",
  "Out of Stock": "Нет в наличии",
  "Minimum Order:": "Мин. заказ:",
  "In stock and ready to ship worldwide": "В наличии, готовы к отправке по всему миру",
  "Back to Products": "Назад к каталогу",
  "Go back": "Назад",
  "Product not found": "Товар не найден",
  "Specifications": "Технические характеристики",
  "Quantity": "Количество",
  "No products found": "Товары не найдены",
  "We couldn't find any products in this category. Please try another category.": "В этой категории товары не найдены. Пожалуйста, выберите другую категорию.",

  // Product Names & Descriptions
  "Jinyu Skyline Boulevard LED Street Lamp": "Уличный светодиодный светильник Jinyu Skyline Boulevard",
  "100W-250W high-output street lamp engineered with a die-cast aluminum housing and IP66 waterproof rating for high-performance municipal, highway, and parking lot illumination.": "Мощный уличный светильник 100-250 Вт в литом алюминиевом корпусе с защитой IP66 для освещения автомагистралей, городских дорог и парковок.",
  "Jinyu Metro Avenue LED Street Lamp": "Уличный светодиодный светильник Jinyu Metro Avenue",
  "80W-200W premium street luminaire designed for highways and urban avenues. Heavy-duty aluminum alloy housing with advanced thermal management.": "Премиальный светильник 80-200 Вт для автомагистралей и городских проспектов. Прочный корпус из алюминиевого сплава с эффективным теплоотводом.",
  "Jinyu Fortune Tree Landscape Lamp": "Ландшафтный светильник Jinyu Fortune Tree",
  "4.0m-6.0m elegant outdoor tree luminaire constructed from galvanized steel and aluminum. Perfect for parks, public plazas, and luxury commercial walkways.": "Элегантный парковый светильник-дерево высотой 4,0-6,0 м из оцинкованной стали и алюминия. Идеален для парков, площадей и прогулочных зон.",
  "Jinyu Van Gogh Trees Landscape Lamp": "Арт-светильник Jinyu Van Gogh Trees",
  "3.5m-5.5m artistic tree structure featuring die-cast aluminum alloy canopy and leaves. Integrates RGB ambient lighting for premium nightscape designs.": "Художественная световая конструкция 3,5-5,5 м с алюминиевыми ветвями и листьями. Встроенная подсветка RGB для вечернего оформления.",
  "Jinyu Angel's Wings Landscape Light": "Ландшафтный светильник Jinyu Angel's Wings",
  "4.5m tall modern landscape sculpture made of premium grade 304 stainless steel. Features a swept-back illuminated form silhouette providing ambient night glow.": "Современная ландшафтная световая скульптура высотой 4,5 м из нержавеющей стали 304 с мягким контурным ночным свечением.",
  "Jinyu Smart Ceiling Light": "Умный потолочный светильник Jinyu",
  "Sleek, low-profile intelligent ceiling lamp. Features customizable color temperatures (3000K-6000K), voice assistant compatibility, and high energy efficiency.": "Тонкий умный потолочный светильник с регулировкой цветовой температуры (3000K-6000K), голосовым управлением и низким энергопотреблением.",
  "Jinyu Luxury Acrylic Panel Light": "Акриловая потолочная панель Jinyu Luxury",
  "Contemporary square ceiling panel light with a high-transmittance luxury acrylic diffuser. Provides glare-free, uniform light for modern office and residential spaces.": "Современная квадратная потолочная панель с рассеивателем из акрила высокой прозрачности для равномерного освещения офисов и домов.",
  "Jinyu Electroplated Wall Lamp": "Настенный светильник с гальванопокрытием Jinyu",
  "Elegant modern wall sconce with a hand-polished electroplated finish. Delivers a soft warm white glow ideal for luxury hallways and dining spaces.": "Элегантное настенное бра с ручной полировкой и гальваническим покрытием. Мягкий теплый свет для холлов и гостиных.",
  "Jinyu Walnut Finish Tri-Color LED Pendant": "Подвесной светодиодный светильник Jinyu Walnut Tri-Color",
  "Minimalistic linear pendant lamp in solid walnut wood finish. Features tri-color LED switching (warm, neutral, cool white) for customizable dining experiences.": "Минималистичный подвесной светильник с отделкой под орех и переключением 3 температур света (теплый, нейтральный, холодный).",
  "Jinyu Heavy Duty Industrial Floodlight": "Промышленный прожектор Jinyu Heavy Duty",
  "High-output industrial LED floodlight built for sports arenas, ports, and construction sites. Features robust IP66 weatherproofing and die-cast aluminum heat sink.": "Высокомощный светодиодный прожектор для стадионов, портов и стройплощадок. Защита IP66 и надежный теплоотвод из литого алюминия.",

  // Specification Keys & Values
  "Wattage": "Мощность",
  "Input Voltage": "Входное напряжение",
  "Color Temperature": "Цветовая температура",
  "IP Rating": "Степень защиты IP",
  "Material": "Материал",
  "Lifespan": "Срок службы",
  "Warranty": "Гарантия",
  "Certifications": "Сертификаты",
  "Beam Angle": "Угол рассеивания",
  "Luminous Flux": "Световой поток",

  // About Page
  "About Jinyu Capital": "О компании Jinyu Capital",
  "Leading Manufacturer of Industrial & Architectural Lighting": "Ведущий производитель промышленного и архитектурного освещения",
  "Established in 2018 in Guangzhou, Jinyu Capital specialized in high-grade LED fixtures, explosion-proof luminaires, and specialized outdoor lighting systems.": "Компания Jinyu Capital основана в 2018 году в Гуанчжоу и специализируется на высококлассных светодиодных и взрывозащищенных светильниках.",
  "Engineering Innovation Industrial Reliability": "Инженерные инновации и промышленная надежность",
  "Jinyu specializes in the design, manufacturing, and supply of explosion-proof lighting and industrial electrical solutions for global markets": "Jinyu разрабатывает, производит и поставляет взрывозащищенное освещение и электротехнические решения для мировых рынков.",
  "Our story": "Наша история",
  "Driven by innovation and quality, Jinyu has developed a complete manufacturing ecosystem covering mold development, die-casting, production, assembly, and OEM/ODM customization.": "Благодаря инновациям Jinyu создала полную производственную экосистему: от пресс-форм и литья до сборки и кастомизации OEM/ODM.",
  "Annual production exceeds 2.4 million units, supported by advanced facilities, experienced engineering teams, and strict quality control systems.": "Годовой объем производства превышает 2,4 млн единиц при строгом контроле качества на каждом этапе.",
  "Backed by 80+ patents and international certifications including ISO, CCC, EX, and ATEX, we deliver reliable solutions for industrial and hazardous environments worldwide.": "Обладая более чем 80 патентами и сертификатами ISO, CCC, EX, ATEX, мы поставляем надежные решения для опасных производственных зон.",
  "Our Core Values": "Наши ценности",
  "The principles that guide our manufacturing processes and client relationships.": "Принципы, на которых строятся наше производство и партнерские отношения.",
  "Precision": "Точность",
  "We maintain strict tolerances and rigorous quality control in every stage of our manufacturing process.": "Мы соблюдаем строгие допуски и стандарты контроля качества на каждом этапе производства.",
  "Innovation": "Инновации",
  "We continuously invest in R&D to develop energy-efficient lighting and smarter, more durable appliances.": "Мы непрерывно инвестируем в R&D для создания энергоэффективных и долговечных световых решений.",
  "Partnership": "Партнерство",
  "We build lasting relationships with our global distributors through transparency and consistent delivery.": "Мы выстраиваем долгосрочные отношения с дистрибьюторами на основе прозрачности и стабильных поставок.",
  "Our Mission": "Наша миссия",
  "Quality Assurance": "Контроль качества",
  "R&D Innovation": "Исследования и разработки",
  "Global Presence": "Глобальное присутствие",

  // Contact Page & Company Address
  "Contact Us": "Связаться с нами",
  "Get in touch": "Связаться с нами",
  "Get in Touch": "Оставайтесь на связи",
  "Have questions about our platform or services? Our team is here to help you get started with professional trading.": "Есть вопросы по продукции или условиям сотрудничества? Наша команда готова помочь вам.",
  "We're here to answer your questions, assist with custom OEM/ODM requests, and support your project requirements.": "Мы готовы ответить на ваши вопросы, помочь с заказами OEM/ODM и поддержать ваш проект.",
  "Send us a message": "Напишите нам",
  "Contact information": "Контактная информация",
  "Office": "Офис",
  "Support hours": "Часы работы",
  "Email": "Эл. почта",
  "Phone": "Телефон",
  "Monday - Friday, 8:00 AM - 6:00 PM EST": "Понедельник - Пятница, 8:00 - 18:00 EST",
  "Unit 119, Building 19, Changfeng International, No. 96 Lixin 12th Road, Xintang Town, Zengcheng District, Guangzhou City": "Блок 119, корпус 19, Changfeng International, ул. Лисинь 12, д. 96, Синьтан, район Цзэнчэн, г. Гуанчжоу",
  "No. 119, Building 19, Changfeng International, 96 Li Xin No. 12 Road, Xin Tang Town, Zengcheng District, Guangzhou City": "Блок 119, корпус 19, Changfeng International, ул. Лисинь 12, д. 96, Синьтан, район Цзэнчэн, г. Гуанчжоу",
  "Need immediate assistance?": "Нужна срочная помощь?",
  "Our support team is available during business hours to help with account setup, platform questions, and technical issues.": "Наша служба поддержки готова помочь вам в рабочие часы по любым техническим и коммерческим вопросам.",
  "Full Name": "Полное имя",
  "Email Address": "Адрес эл. почты",
  "Phone Number": "Номер телефона",
  "Company Name": "Название компании",
  "Project Type / Details": "Тип проекта / Детали",
  "Send Message": "Отправить сообщение",
  "Your full name": "Ваше имя и фамилия",
  "your.email@example.com": "your.email@example.com",
  "Your company name": "Название вашей компании",
  "Tell us more about your inquiry...": "Опишите ваш запрос или проект подробнее...",
  "Name is required": "Укажите ваше имя",
  "Email is required": "Укажите адрес эл. почты",
  "Please enter a valid email address": "Введите корректный адрес эл. почты",
  "Message is required": "Введите текст сообщения",
  "Message must be at least 10 characters": "Сообщение должно содержать не менее 10 символов",
  "Message sent successfully. Our sales team will contact you shortly.": "Сообщение успешно отправлено! Наш специалист свяжется с вами в ближайшее время.",
  "Failed to send message. Please try again.": "Не удалось отправить сообщение. Попробуйте еще раз.",
  "Thank you for reaching out! We will reply within 24 hours.": "Спасибо за обращение! Мы ответим в течение 24 часов.",

  // Distributor Page & Form
  "Partner with Jinyu Capital to bring high-quality, innovative lighting and appliance solutions to your local market. Fill out the application below to start the conversation.": "Станьте партнером Jinyu Capital и поставляйте передовое осветительное оборудование на ваш региональный рынок. Заполните форму заявки.",
  "Join our global network of authorized regional distributors and partners.": "Присоединяйтесь к международной сети авторизованных дистрибьюторов и партнеров.",
  "Company Information": "Информация о компании",
  "Company Name *": "Название компании *",
  "Country / Region *": "Страна / Регион *",
  "Business Type *": "Тип деятельности *",
  "Select business type": "Выберите тип деятельности",
  "Wholesaler": "Оптовик",
  "Contractor": "Подрядчик",
  "Brand": "Торговая марка",
  "Other": "Другое",
  "Contact Details": "Контактные данные",
  "Contact Person *": "Контактное лицо *",
  "Full name": "Полное имя",
  "Email Address *": "Адрес эл. почты *",
  "Phone Number *": "Номер телефона *",
  "Business Profile": "Профиль бизнеса",
  "Current Business Experience": "Текущий опыт и направления работы",
  "Briefly describe your current operations, years in business, and market reach...": "Кратко опишите ваш текущий бизнес, опыт на рынке и географию...",
  "Product Categories of Interest": "Интересующие категории продукции",
  "Which Jinyu product lines are you most interested in distributing?": "Какие линейки продукции Jinyu вас интересуют больше всего?",
  "Additional Information": "Дополнительная информация",
  "Any other details you'd like to share with our team...": "Любые другие детали, которые вы хотите указать...",
  "Submit Application": "Отправить заявку",
  "Submitting Application...": "Отправка заявки...",
  "Application submitted successfully. Our team will review and contact you shortly.": "Заявка успешно отправлена! Наша команда рассмотрит ее и свяжется с вами.",
  "Please fill in all required fields correctly.": "Пожалуйста, корректно заполните все обязательные поля.",
  "Company name is required": "Укажите название компании",
  "Contact person is required": "Укажите контактное лицо",
  "Country/Region is required": "Укажите страну/регион",
  "Business type is required": "Выберите тип деятельности",
  "Phone number is required": "Укажите номер телефона",
  "e.g. Global Lighting Corp": "напр. Global Lighting Corp",
  "e.g. United States": "напр. Россия / Казахстан / Беларусь",
  "work@company.com": "work@company.com",

  // Request a Quote Page
  "B2B & Commercial Inquiry": "B2B и коммерческие запросы",
  "Request a Project Quote": "Запросить коммерческое предложение",
  "Submit your architectural, street, or landscape lighting requirements below. Our engineering and sales team will review your specifications and provide a competitive wholesale quote.": "Оставьте заявку на проект освещения. Наши инженеры подготовят конкурентное оптовое предложение с расчетом.",
  "Quote Request Received": "Запрос на КП получен",
  "Thank you for submitting your project specifications. Our sales engineers are reviewing your request and will contact you within 24 business hours.": "Спасибо за предоставленные характеристики! Наши инженеры свяжутся с вами в течение 24 рабочих часов.",
  "Submit another quote request": "Отправить еще один запрос",
  "First Name *": "Имя *",
  "Last Name *": "Фамилия *",
  "Project Type *": "Тип проекта *",
  "Street & Highway Lighting": "Уличное и магистральное освещение",
  "Landscape & Architectural": "Ландшафтная и архитектурная подсветка",
  "Industrial Floodlights": "Промышленные прожекторы",
  "Custom OEM/ODM Manufacturing": "Контрактное производство OEM/ODM",
  "Product of Interest": "Интересующий продукт",
  "Est. Quantity *": "Ориентировочное количество *",
  "Project Specifications & Details *": "Технические требования и спецификация проекта *",
  "Describe your project, required certifications (CE, RoHS, UL), voltage specs, and any customization requests...": "Опишите проект, требуемые сертификаты (CE, RoHS, ATEX), напряжение и пожелания по кастомизации...",
  "SUBMIT QUOTE REQUEST": "ОТПРАВИТЬ ЗАПРОС НА КП",
  "SENDING REQUEST...": "ОТПРАВКА ЗАПРОСА...",
  "Engineering Standards": "Инженерные стандарты",
  "Jinyu Capital operates state-of-the-art aluminum die-casting, automated SMT lines, and photometric testing labs to ensure pro-grade durability.": "Jinyu Capital располагает собственным цехом литья под давлением, линиями SMT и лабораторией фотометрии.",
  "Commercial Warranty": "Гарантия на коммерческие проекты",
  "Every commercial lighting product includes a 5-year replacement warranty, full certificate compliance support, and free local shipping coordination.": "На всю коммерческую продукцию предоставляется 5-летняя гарантия и полный пакет сертификатов.",
  "24-Hour Turnaround": "Ответ в течение 24 часов",
  "Our sales engineers review photometrics files, BOM requirements, and logistics paths to deliver accurate quote sheets within 1 business day.": "Наши инженеры изучают фотометрические данные и спецификации, формируя расчет за 1 рабочий день.",
  "Need Assistance?": "Нужна консультация?",
  "For custom OEM molds or general questions about supply chain scheduling, email our support directly at": "По вопросам пресс-форм OEM или срокам производства пишите нам на",

  // CTA & Blog
  "Partner with a reliable manufacturer": "Надежное партнерство с производителем",
  "Whether you need OEM services or bulk orders of our standard product lines, our team is ready to support your business.": "Независимо от того, требуется ли вам OEM-производство или оптовая партия стандартных линеек, мы готовы помочь.",
  "Latest news & insights": "Новости и статьи отрасли",
  "Stay updated with our latest technology breakthroughs, lighting guides, and company announcements.": "Будьте в курсе наших технологических разработок, руководств по освещению и новостей компании.",
  "Read all insights": "Все статьи",
  "Read More →": "Читать далее →",
  "Industry Insights & News": "Новости и статьи отрасли",
  "Stay informed with the latest trends in industrial manufacturing, explosion-proof technology, and robust engineering solutions.": "Будьте в курсе актуальных трендов промышленного производства, взрывозащиты и инженерных решений.",
  "All": "Все",
  "Industrial Equipment": "Промышленное оборудование",
  "Industry News & Insights": "Новости и статьи",
  "OEM/ODM Solutions": "Решения OEM/ODM",
  "Product Updates": "Обновления продукции",
  "No articles found": "Статьи не найдены",
  "No articles match your current filters or search terms.": "По заданным фильтрам или поисковому запросу ничего не найдено.",
  "Clear Filters": "Сбросить фильтры",
  "Loading article...": "Загрузка статьи...",
  "Article Not Found": "Статья не найдена",
  "The article you are looking for does not exist or may have been moved.": "Запрошенная статья не существует или была перемещена.",
  "Back to Blog": "Назад в блог",
  "Back": "Назад",
  "By": "Автор:",
};

// French Dictionary
const fr: Record<string, string> = {
  // Navigation & General
  "Home": "Accueil",
  "About": "À propos",
  "Products": "Produits",
  "Blog": "Blog",
  "Distributor": "Distributeurs",
  "Contact": "Contact",
  "Request a quote": "Demander un devis",
  "Request a Quote": "Demander un devis",
  "Explore products": "Explorer les produits",
  "Contact sales": "Contacter les ventes",
  "Contact our sales team": "Contacter notre équipe commerciale",
  "Quick links": "Liens rapides",
  "Follow us": "Suivez-nous",
  "Language": "Langue",
  "Chinese": "中文",
  "English": "English",
  "Russian": "Русский",
  "French": "Français",
  "Quote": "Devis",
  "Our Story": "Notre histoire",
  "Cart": "Panier",

  // Hero & Brand
  "Manufacturing Excellence From China To The World": "Excellence de fabrication de la Chine au monde entier",
  "Jinyu combines manufacturing, OEM production, product development, and global supply chain solutions for distributors, wholesalers, contractors, and brands worldwide.": "Jinyu combine fabrication, production OEM, développement de produits et solutions de chaîne d'approvisionnement mondiale.",
  "Your trusted manufacturer of premium lighting equipment and appliances, delivering engineering excellence and quality since 2018.": "Votre fabricant de confiance d'équipements d'éclairage haut de gamme depuis 2018.",
  "Looking to expand your business?": "Vous souhaitez développer votre entreprise ?",
  "Become a Distributor": "Devenir distributeur",
  "Become a Global Distributor": "Devenir un distributeur mondial",
  "Explore Catalogue": "Explorer le catalogue",
  "Apply Now": "Postuler maintenant",
  "All rights reserved.": "Tous droits réservés.",
  "Website design by SpaceMinds": "Design du site web par SpaceMinds",
  "Privacy Policy": "Politique de confidentialité",
  "Terms of Service": "Conditions d'utilisation",

  // Stats
  "Product lines": "Gammes de produits",
  "Sq.m facility": "m² d'installations",
  "Countries exported": "Pays d'exportation",
  "9001 Certified": "Certifié ISO 9001",

  // Manufacturing Section
  "Manufacturing Excellence": "Excellence de fabrication",
  "Manufacturing excellence": "Excellence de fabrication",
  "Built on a foundation of engineering expertise, we deliver reliable products that meet the demands of global markets. Our Guangzhou facility represents the pinnacle of modern production capabilities.": "Forts de notre expertise en ingénierie, nous concevons des produits fiables conformes aux exigences internationales. Notre site de Guangzhou illustre l'excellence de la production moderne.",
  "Advanced manufacturing": "Fabrication de pointe",
  "State-of-the-art production facilities equipped with automated assembly lines for precision and scale.": "Installations de pointe dotées de lignes d'assemblage automatisées pour une précision et une capacité optimales.",
  "Rigorous quality control": "Contrôle qualité rigoureux",
  "Comprehensive testing protocols ensuring every appliance and lighting fixture meets international safety standards.": "Protocoles de tests stricts garantissant que chaque luminaire respecte les normes internationales de sécurité.",
  "Innovative engineering": "Ingénierie innovante",
  "Dedicated R&D team continuously developing energy-efficient and smart technology solutions.": "Équipe R&D dédiée développant en continu des technologies intelligentes et éco-énergétiques.",
  "Guangzhou Production Facility": "Site de production de Guangzhou",
  "High-performance manufacturing, assembly, and testing workshop": "Atelier de fabrication, assemblage et essais haute performance",
  "Sq.m Production Area": "m² de surface de production",

  // Showcase Products
  "Featured Product Lines": "Gammes de produits vedettes",
  "Featured product lines": "Gammes de produits vedettes",
  "Explore our signature street lighting collections, engineered for superior outdoor performance, longevity, and aesthetic appeal.": "Découvrez nos collections d'éclairage public emblématiques, conçues pour une performance extérieure durable et esthétique.",
  "View all products": "Voir tous les produits",
  "Skyline Boulevard Series": "Série Skyline Boulevard",
  "Designed for modern cities, business districts, residential communities, and municipal infrastructure projects, the Skyline Boulevard Series combines contemporary aesthetics with exceptional lighting performance. Its durable construction, energy-efficient LED technology, and weather-resistant design ensure reliable illumination while enhancing the appearance of any roadway.": "Conçue pour les métropoles modernes, quartiers d'affaires et infrastructures publiques, la série Skyline Boulevard allie esthétique contemporaine et performance lumineuse. Sa conception robuste et éco-énergétique assure un éclairage fiable tout en valorisant la voirie.",
  "Urban Road Lighting Series": "Série Urban Road Lighting",
  "Reliable LED street lighting for urban roads, parks, estates, and commercial projects. Designed for strong illumination, energy efficiency, and long service life.": "Éclairage public LED fiable pour routes urbaines, parcs et zones commerciales. Conçu pour une luminosité optimale, une haute efficacité et une longue durée de vie.",
  "Metro Avenue Series": "Série Metro Avenue",
  "Modern LED street lighting for highways, city roads, business parks, and residential developments. Built for efficient illumination, durability, and long-lasting outdoor performance.": "Éclairage public LED moderne pour autoroutes, avenues et parcs d'activités. Conçu pour un éclairage efficace, robuste et durable en extérieur.",

  // Product Catalog
  "Product Portfolio": "Gamme de produits",
  "Browse our focused range of high-performance municipal and commercial lighting solutions, engineered for precision, durability, and contemporary aesthetics.": "Parcourez notre gamme ciblée de solutions d'éclairage municipal et commercial haute performance.",
  "All Categories": "Toutes les catégories",
  "All Products": "Tous les produits",
  "Street Lamps": "Lampadaires urbains",
  "Landscape Lamps": "Éclairage paysager",
  "Ceiling Lights": "Plafonniers",
  "Wall Sconces": "Appliques murales",
  "Pendant Lamps": "Suspensions",
  "Industrial Lighting": "Éclairage industriel",
  "Explosion-Proof Lighting": "Éclairage antidéflagrant",
  "Street Lighting": "Éclairage public",
  "Landscape Lighting": "Éclairage paysager",
  "Commercial & Industrial Lighting": "Éclairage commercial et industriel",
  "Landscape & Urban Lamps": "Éclairage paysager et urbain",
  "OEM / ODM Custom Manufacturing": "Fabrication sur mesure OEM / ODM",
  "Search products...": "Rechercher des produits...",
  "Sort by": "Trier par",
  "Featured": "En vedette",
  "Price: Low to High": "Prix : du + bas au + haut",
  "Price: High to Low": "Prix : du + haut au + bas",
  "View Details": "Voir les détails",
  "Add to Cart": "Ajouter au panier",
  "In Stock": "En stock",
  "Out of Stock": "Rupture de stock",
  "Minimum Order:": "Commande min :",
  "In stock and ready to ship worldwide": "En stock et prêt à être expédié dans le monde entier",
  "Back to Products": "Retour aux produits",
  "Go back": "Retour",
  "Product not found": "Produit non trouvé",
  "Specifications": "Spécifications techniques",
  "Quantity": "Quantité",
  "No products found": "Aucun produit trouvé",
  "We couldn't find any products in this category. Please try another category.": "Aucun produit trouvé dans cette catégorie. Veuillez essayer une autre catégorie.",

  // Product Names & Descriptions
  "Jinyu Skyline Boulevard LED Street Lamp": "Lampadaire LED Jinyu Skyline Boulevard",
  "100W-250W high-output street lamp engineered with a die-cast aluminum housing and IP66 waterproof rating for high-performance municipal, highway, and parking lot illumination.": "Lampadaire haute puissance 100W-250W avec boîtier en fonte d'aluminium et indice de protection IP66 pour routes urbaines, autoroutes et parkings.",
  "Jinyu Metro Avenue LED Street Lamp": "Lampadaire LED Jinyu Metro Avenue",
  "80W-200W premium street luminaire designed for highways and urban avenues. Heavy-duty aluminum alloy housing with advanced thermal management.": "Luminaire urbain haut de gamme 80W-200W conçu pour autoroutes et grandes avenues. Boîtier robuste en alliage d'aluminium avec gestion thermique avancée.",
  "Jinyu Fortune Tree Landscape Lamp": "Luminaire paysager Jinyu Fortune Tree",
  "4.0m-6.0m elegant outdoor tree luminaire constructed from galvanized steel and aluminum. Perfect for parks, public plazas, and luxury commercial walkways.": "Luminaire d'extérieur élégant en forme d'arbre de 4,0 m à 6,0 m en acier galvanisé et aluminium. Idéal pour parcs, places publiques et allées commerciales.",
  "Jinyu Van Gogh Trees Landscape Lamp": "Luminaire artistique Jinyu Van Gogh Trees",
  "3.5m-5.5m artistic tree structure featuring die-cast aluminum alloy canopy and leaves. Integrates RGB ambient lighting for premium nightscape designs.": "Structure d'arbre artistique de 3,5 m à 5,5 m avec canopée et feuilles en fonte d'aluminium. Éclairage d'ambiance RVB intégré pour paysages nocturnes.",
  "Jinyu Angel's Wings Landscape Light": "Luminaire paysager Jinyu Angel's Wings",
  "4.5m tall modern landscape sculpture made of premium grade 304 stainless steel. Features a swept-back illuminated form silhouette providing ambient night glow.": "Sculpture lumineuse moderne de 4,5 m en acier inoxydable 304 de qualité supérieure, offrant une silhouette lumineuse douce pour la nuit.",
  "Jinyu Smart Ceiling Light": "Plafonnier intelligent Jinyu",
  "Sleek, low-profile intelligent ceiling lamp. Features customizable color temperatures (3000K-6000K), voice assistant compatibility, and high energy efficiency.": "Plafonnier intelligent au profil épuré. Température de couleur réglable (3000K-6000K), compatible assistants vocaux et haute efficacité énergétique.",
  "Jinyu Luxury Acrylic Panel Light": "Panneau acrylique de luxe Jinyu",
  "Contemporary square ceiling panel light with a high-transmittance luxury acrylic diffuser. Provides glare-free, uniform light for modern office and residential spaces.": "Panneau de plafond carré contemporain avec diffuseur acrylique haute transmission. Éclairage homogène et sans éblouissement pour bureaux et résidences.",
  "Jinyu Electroplated Wall Lamp": "Applique murale électrozinguée Jinyu",
  "Elegant modern wall sconce with a hand-polished electroplated finish. Delivers a soft warm white glow ideal for luxury hallways and dining spaces.": "Applique murale moderne et élégante avec finition galvanisée polie à la main. Émet une lueur blanc chaud idéale pour couloirs et salles à manger.",
  "Jinyu Walnut Finish Tri-Color LED Pendant": "Suspension LED tricolore finition noyer Jinyu",
  "Minimalistic linear pendant lamp in solid walnut wood finish. Features tri-color LED switching (warm, neutral, cool white) for customizable dining experiences.": "Suspension linéaire minimaliste en finition noyer. 3 températures de couleur commutables (chaud, neutre, blanc froid) pour une ambiance personnalisée.",
  "Jinyu Heavy Duty Industrial Floodlight": "Projecteur industriel renforcé Jinyu",
  "High-output industrial LED floodlight built for sports arenas, ports, and construction sites. Features robust IP66 weatherproofing and die-cast aluminum heat sink.": "Projecteur LED industriel haute puissance conçu pour complexes sportifs, ports et chantiers. Étanchéité IP66 et dissipateur thermique en fonte d'aluminium.",

  // Specification Keys & Values
  "Wattage": "Puissance",
  "Input Voltage": "Tension d'entrée",
  "Color Temperature": "Température de couleur",
  "IP Rating": "Indice de protection IP",
  "Material": "Matériau",
  "Lifespan": "Durée de vie",
  "Warranty": "Garantie",
  "Certifications": "Certifications",
  "Beam Angle": "Angle de faisceau",
  "Luminous Flux": "Flux lumineux",

  // About Page
  "About Jinyu Capital": "À propos de Jinyu Capital",
  "Leading Manufacturer of Industrial & Architectural Lighting": "Fabricant leader d'éclairage industriel et architectural",
  "Established in 2018 in Guangzhou, Jinyu Capital specialized in high-grade LED fixtures, explosion-proof luminaires, and specialized outdoor lighting systems.": "Fondée en 2018 à Guangzhou, Jinyu Capital est spécialisée dans les luminaires LED haute qualité et antidéflagrants.",
  "Engineering Innovation Industrial Reliability": "Innovation d'ingénierie et fiabilité industrielle",
  "Jinyu specializes in the design, manufacturing, and supply of explosion-proof lighting and industrial electrical solutions for global markets": "Jinyu est spécialisé dans la conception, la fabrication et la fourniture d'éclairage antidéflagrant et de solutions électriques industrielles.",
  "Our story": "Notre histoire",
  "Driven by innovation and quality, Jinyu has developed a complete manufacturing ecosystem covering mold development, die-casting, production, assembly, and OEM/ODM customization.": "Guidée par l'innovation et la qualité, Jinyu a développé un écosystème de fabrication complet : conception de moules, moulage sous pression, assemblage et personnalisation OEM/ODM.",
  "Annual production exceeds 2.4 million units, supported by advanced facilities, experienced engineering teams, and strict quality control systems.": "Notre production annuelle dépasse 2,4 millions d'unités grâce à nos installations modernes et notre contrôle qualité rigoureux.",
  "Backed by 80+ patents and international certifications including ISO, CCC, EX, and ATEX, we deliver reliable solutions for industrial and hazardous environments worldwide.": "Avec plus de 80 brevets et certifications internationales (ISO, CCC, EX, ATEX), nous fournissons des solutions fiables pour les environnements industriels sévères.",
  "Our Core Values": "Nos valeurs fondamentales",
  "The principles that guide our manufacturing processes and client relationships.": "Les principes directeurs de nos processus de fabrication et relations partenaires.",
  "Precision": "Précision",
  "We maintain strict tolerances and rigorous quality control in every stage of our manufacturing process.": "Nous appliquons des tolérances strictes et un contrôle qualité rigoureux à chaque étape de production.",
  "Innovation": "Innovation",
  "We continuously invest in R&D to develop energy-efficient lighting and smarter, more durable appliances.": "Nous investissons continuellement en R&D pour développer des éclairages éco-énergétiques et performants.",
  "Partnership": "Partenariat",
  "We build lasting relationships with our global distributors through transparency and consistent delivery.": "Nous bâtissons des partenariats durables avec nos distributeurs mondiaux grâce à la transparence et la fiabilité.",
  "Our Mission": "Notre mission",
  "Quality Assurance": "Assurance qualité",
  "R&D Innovation": "Recherche et Innovation",
  "Global Presence": "Présence mondiale",

  // Contact Page & Company Address
  "Contact Us": "Contactez-nous",
  "Get in touch": "Prendre contact",
  "Get in Touch": "Prendre contact",
  "Have questions about our platform or services? Our team is here to help you get started with professional trading.": "Des questions sur nos produits ou services ? Notre équipe est à votre écoute pour vous accompagner.",
  "We're here to answer your questions, assist with custom OEM/ODM requests, and support your project requirements.": "Nous sommes à votre disposition pour répondre à vos questions et traiter vos demandes OEM/ODM.",
  "Send us a message": "Envoyez-nous un message",
  "Contact information": "Informations de contact",
  "Office": "Bureau",
  "Support hours": "Heures d'ouverture",
  "Email": "E-mail",
  "Phone": "Téléphone",
  "Monday - Friday, 8:00 AM - 6:00 PM EST": "Lundi - Vendredi, 8h00 - 18h00 EST",
  "Unit 119, Building 19, Changfeng International, No. 96 Lixin 12th Road, Xintang Town, Zengcheng District, Guangzhou City": "Unité 119, Bâtiment 19, Changfeng International, N° 96 Lixin 12th Road, Xintang, District de Zengcheng, Guangzhou",
  "No. 119, Building 19, Changfeng International, 96 Li Xin No. 12 Road, Xin Tang Town, Zengcheng District, Guangzhou City": "Unité 119, Bâtiment 19, Changfeng International, N° 96 Lixin 12th Road, Xintang, District de Zengcheng, Guangzhou",
  "Need immediate assistance?": "Besoin d'une assistance immédiate ?",
  "Our support team is available during business hours to help with account setup, platform questions, and technical issues.": "Notre équipe technique et commerciale est disponible pendant les heures ouvrables pour vous assister.",
  "Full Name": "Nom complet",
  "Email Address": "Adresse e-mail",
  "Phone Number": "Numéro de téléphone",
  "Company Name": "Nom de l'entreprise",
  "Project Type / Details": "Type de projet / Détails",
  "Send Message": "Envoyer le message",
  "Your full name": "Votre nom complet",
  "your.email@example.com": "votre.email@exemple.com",
  "Your company name": "Nom de votre entreprise",
  "Tell us more about your inquiry...": "Dites-nous en plus sur votre projet ou votre demande...",
  "Name is required": "Le nom est requis",
  "Email is required": "L'e-mail est requis",
  "Please enter a valid email address": "Veuillez entrer une adresse e-mail valide",
  "Message is required": "Le message est requis",
  "Message must be at least 10 characters": "Le message doit comporter au moins 10 caractères",
  "Message sent successfully. Our sales team will contact you shortly.": "Message envoyé avec succès ! Notre équipe commerciale vous recontactera rapidement.",
  "Failed to send message. Please try again.": "Échec de l'envoi. Veuillez réessayer.",
  "Thank you for reaching out! We will reply within 24 hours.": "Merci de nous avoir contactés ! Nous vous répondrons sous 24h.",

  // Distributor Page & Form
  "Partner with Jinyu Capital to bring high-quality, innovative lighting and appliance solutions to your local market. Fill out the application below to start the conversation.": "Devenez partenaire de Jinyu Capital pour distribuer des solutions d'éclairage innovantes sur votre marché. Remplissez le formulaire ci-dessous.",
  "Join our global network of authorized regional distributors and partners.": "Rejoignez notre réseau mondial de distributeurs agréés et de partenaires régionaux.",
  "Company Information": "Informations sur l'entreprise",
  "Company Name *": "Nom de l'entreprise *",
  "Country / Region *": "Pays / Région *",
  "Business Type *": "Type d'activité *",
  "Select business type": "Sélectionnez le type d'activité",
  "Wholesaler": "Grossiste",
  "Contractor": "Entrepreneur / Installateur",
  "Brand": "Marque",
  "Other": "Autre",
  "Contact Details": "Coordonnées de contact",
  "Contact Person *": "Personne à contacter *",
  "Full name": "Nom complet",
  "Email Address *": "Adresse e-mail *",
  "Phone Number *": "Numéro de téléphone *",
  "Business Profile": "Profil de l'entreprise",
  "Current Business Experience": "Expérience et activité actuelle",
  "Briefly describe your current operations, years in business, and market reach...": "Décrivez brièvement votre activité, années d'expérience et couverture de marché...",
  "Product Categories of Interest": "Catégories de produits souhaitées",
  "Which Jinyu product lines are you most interested in distributing?": "Quelles gammes Jinyu souhaitez-vous distribuer en priorité ?",
  "Additional Information": "Informations complémentaires",
  "Any other details you'd like to share with our team...": "Autres détails ou précisions que vous souhaitez nous transmettre...",
  "Submit Application": "Soumettre la candidature",
  "Submitting Application...": "Envoi de la candidature...",
  "Application submitted successfully. Our team will review and contact you shortly.": "Candidature envoyée avec succès ! Notre équipe examinera votre demande et vous recontactera rapidement.",
  "Please fill in all required fields correctly.": "Veuillez remplir correctement tous les champs obligatoires.",
  "Company name is required": "Le nom de l'entreprise est requis",
  "Contact person is required": "Le nom du contact est requis",
  "Country/Region is required": "Le pays/région est requis",
  "Business type is required": "Le type d'activité est requis",
  "Phone number is required": "Le numéro de téléphone est requis",
  "e.g. Global Lighting Corp": "ex. Global Lighting Corp",
  "e.g. United States": "ex. France / Belgique / Canada",
  "work@company.com": "contact@entreprise.com",

  // Request a Quote Page
  "B2B & Commercial Inquiry": "Demande B2B et commerciale",
  "Request a Project Quote": "Demander un devis de projet",
  "Submit your architectural, street, or landscape lighting requirements below. Our engineering and sales team will review your specifications and provide a competitive wholesale quote.": "Soumettez vos besoins en éclairage architectural, public ou paysager. Notre équipe commerciale vous fournira un devis adapté et compétitif.",
  "Quote Request Received": "Demande de devis reçue",
  "Thank you for submitting your project specifications. Our sales engineers are reviewing your request and will contact you within 24 business hours.": "Merci de nous avoir transmis votre cahier des charges ! Nos ingénieurs vous répondront dans les 24 heures ouvrées.",
  "Submit another quote request": "Soumettre une autre demande de devis",
  "First Name *": "Prénom *",
  "Last Name *": "Nom *",
  "Project Type *": "Type de projet *",
  "Street & Highway Lighting": "Éclairage public et autoroutier",
  "Landscape & Architectural": "Éclairage architectural et paysager",
  "Industrial Floodlights": "Projecteurs industriels",
  "Custom OEM/ODM Manufacturing": "Fabrication sur mesure OEM/ODM",
  "Product of Interest": "Produit d'intérêt",
  "Est. Quantity *": "Quantité estimée *",
  "Project Specifications & Details *": "Spécifications techniques du projet *",
  "Describe your project, required certifications (CE, RoHS, UL), voltage specs, and any customization requests...": "Décrivez votre projet, certifications requises (CE, RoHS, ATEX), tensions et demandes de personnalisation...",
  "SUBMIT QUOTE REQUEST": "SOUMETTRE LA DEMANDE DE DEVIS",
  "SENDING REQUEST...": "ENVOI EN COURS...",
  "Engineering Standards": "Normes d'ingénierie",
  "Jinyu Capital operates state-of-the-art aluminum die-casting, automated SMT lines, and photometric testing labs to ensure pro-grade durability.": "Jinyu Capital dispose d'ateliers de moulage sous pression, de lignes SMT automatisées et de laboratoires photométriques certifiés.",
  "Commercial Warranty": "Garantie commerciale",
  "Every commercial lighting product includes a 5-year replacement warranty, full certificate compliance support, and free local shipping coordination.": "Chaque produit d'éclairage commercial bénéficie d'une garantie de 5 ans et d'une conformité totale aux normes.",
  "24-Hour Turnaround": "Réponse sous 24h",
  "Our sales engineers review photometrics files, BOM requirements, and logistics paths to deliver accurate quote sheets within 1 business day.": "Nos ingénieurs analysent vos fichiers photométriques et contraintes logistiques pour fournir un devis en 1 jour ouvré.",
  "Need Assistance?": "Besoin d'aide ?",
  "For custom OEM molds or general questions about supply chain scheduling, email our support directly at": "Pour les moules OEM sur mesure ou le calendrier d'approvisionnement, écrivez-nous à",

  // CTA & Blog
  "Partner with a reliable manufacturer": "Devenez partenaire d'un fabricant fiable",
  "Whether you need OEM services or bulk orders of our standard product lines, our team is ready to support your business.": "Que vous ayez besoin de services OEM ou de commandes en gros, notre équipe est prête à accompagner votre projet.",
  "Latest news & insights": "Dernières actualités et perspectives",
  "Stay updated with our latest technology breakthroughs, lighting guides, and company announcements.": "Restez informé de nos avancées technologiques, guides d'éclairage et annonces d'entreprise.",
  "Read all insights": "Toutes les actualités",
  "Read More →": "En savoir plus →",
  "Industry Insights & News": "Actualités et perspectives du secteur",
  "Stay informed with the latest trends in industrial manufacturing, explosion-proof technology, and robust engineering solutions.": "Suivez les dernières tendances de l'industrie, des technologies antidéflagrantes et de l'ingénierie avancée.",
  "All": "Tous",
  "Industrial Equipment": "Équipements industriels",
  "Industry News & Insights": "Actualités & Analyses",
  "OEM/ODM Solutions": "Solutions OEM/ODM",
  "Product Updates": "Mises à jour produits",
  "No articles found": "Aucun article trouvé",
  "No articles match your current filters or search terms.": "Aucun article ne correspond à vos critères de recherche ou de filtrage.",
  "Clear Filters": "Effacer les filtres",
  "Loading article...": "Chargement de l'article...",
  "Article Not Found": "Article non trouvé",
  "The article you are looking for does not exist or may have been moved.": "L'article que vous recherchez n'existe pas ou a été déplacé.",
  "Back to Blog": "Retour au blog",
  "Back": "Retour",
  "By": "Par",
};

const WebsiteLanguageContext = createContext<WebsiteLanguageContextValue | null>(null);

function subscribeToLanguage(callback: () => void) {
  window.addEventListener("storage", callback);
  window.addEventListener(LANGUAGE_CHANGE_EVENT, callback);
  return () => {
    window.removeEventListener("storage", callback);
    window.removeEventListener(LANGUAGE_CHANGE_EVENT, callback);
  };
}

function getLanguageSnapshot(): WebsiteLanguage {
  const saved = window.localStorage.getItem(STORAGE_KEY);
  return saved === "zh" || saved === "ru" || saved === "fr" || saved === "en" ? saved : "en";
}

function getServerLanguageSnapshot(): WebsiteLanguage {
  return "en";
}

function interpolate(message: string, values?: TranslationValues) {
  if (!values) return message;
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    message,
  );
}

export function WebsiteLanguageProvider({ children }: { children: React.ReactNode }) {
  // Default for the public website is English ("en")
  const language = useSyncExternalStore(
    subscribeToLanguage,
    getLanguageSnapshot,
    getServerLanguageSnapshot,
  );

  useEffect(() => {
    const previousLanguage = document.documentElement.lang;
    document.documentElement.lang = language === "zh" ? "zh-CN" : language === "ru" ? "ru" : language === "fr" ? "fr" : "en";
    return () => {
      document.documentElement.lang = previousLanguage;
    };
  }, [language]);

  const setLanguage = useCallback((nextLanguage: WebsiteLanguage) => {
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT));
  }, []);

  const t = useCallback(
    (message: string, values?: TranslationValues) => {
      if (!message) return "";
      if (language === "en") return interpolate(message, values);
      const dict = language === "zh" ? zh : language === "ru" ? ru : language === "fr" ? fr : zh;
      const translated = dict[message] ?? message;
      return interpolate(translated, values);
    },
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <WebsiteLanguageContext.Provider value={value}>
      {children}
    </WebsiteLanguageContext.Provider>
  );
}

export function useWebsiteLanguage() {
  const context = useContext(WebsiteLanguageContext);
  if (!context) throw new Error("useWebsiteLanguage must be used inside WebsiteLanguageProvider");
  return context;
}
